#!/usr/bin/env python3
"""Exact strip benchmark of avgE and isolated-Z at critical state points.

This extends ``exact_strip_entropy.py`` by adding vacancies, the nondirectional
contact attraction, and the manuscript's positive occupancy cost ``mu``.  The
full orientational model is solved exactly on infinite W=3 and W=4 strips.

The exact Gibbs measure generated by the Perron vectors is a stationary Markov
chain of columns.  We decompose its entropy rate exactly as

    H(C'|C) = H(O'|C) + H(R'|C,O'),

where O' is the occupancy pattern of the new column and R' its occupied-site
orientations.  The second term is a nonnegative, environment-conditioned
internal entropy.  Per occupied particle it is compared with avgE (zero) and
isolated-Z (ln(q)).
"""

from __future__ import annotations

import argparse
import csv
import itertools
import math
from dataclasses import dataclass
from pathlib import Path

import matplotlib
import numpy as np
from scipy.linalg import eig
from scipy.optimize import brentq

matplotlib.use("Agg")
import matplotlib.pyplot as plt


@dataclass(frozen=True)
class PatchModel:
    name: str
    labels: tuple[str, ...]
    north: tuple[int, ...]
    east: tuple[int, ...]
    south: tuple[int, ...]
    west: tuple[int, ...]

    @property
    def q(self) -> int:
        return len(self.labels)


STICK = PatchModel(
    "stick",
    ("H", "V"),
    (0, 1),
    (1, 0),
    (0, 1),
    (1, 0),
)

LSHAPE = PatchModel(
    "L-shaped",
    ("NE", "ES", "SW", "WN"),
    (1, 0, 0, 1),
    (1, 1, 0, 0),
    (0, 1, 1, 0),
    (0, 0, 1, 1),
)

MODELS = (STICK, LSHAPE)


# The nonzero-directional points are exact tuples printed in the manuscript's
# original L=10 critical-line logs:
#     theta* = (eps_nd, eps_d, mu, Lambda, M_c, s).
# A subset was also checked in the later finite-size-scaling campaign.  The
# higher-coupling tuples are successful points from the original MC critical-
# line continuation; absence of the same secondary FSS check at every point is
# not treated here as a failure or as grounds to exclude the point.
# eps_d=0 uses the exact square-lattice-gas critical anchor rather than the
# finite-MC value in the logs.
LATTICE_GAS_CRITICAL = 2.0 * math.log(1.0 + math.sqrt(2.0))
CRITICAL_POINTS = {
    "stick": (
        dict(label="exact lattice-gas anchor", eps_nd=LATTICE_GAS_CRITICAL,
             eps_d=0.0, mu=2.0 * LATTICE_GAS_CRITICAL + math.log(2.0),
             source="exact 2D lattice-gas anchor",
             critical_input_status="exact anchor"),
        dict(label="weak directional", eps_nd=1.5127171674459416,
             eps_d=1.0, mu=4.293145650376483,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC + FSS-checked"),
        dict(label="intermediate directional", eps_nd=1.2798462604243968,
             eps_d=1.8, mu=4.41489350074435,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC + FSS-checked"),
        dict(label="upper FSS-checked directional", eps_nd=1.2148321910996245,
             eps_d=1.96, mu=4.4165650449707385,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC + FSS-checked"),
        dict(label="high directional", eps_nd=1.105411785087950,
             eps_d=2.2, mu=4.429688173189433,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=0.907749349042405,
             eps_d=2.6, mu=4.438929708656842,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=0.784388800988156,
             eps_d=3.0, mu=4.540452889308368,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=0.566073425563976,
             eps_d=4.0, mu=5.108573651020729,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=0.505157675079953,
             eps_d=5.0, mu=6.017271743932018,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=0.390833241320132,
             eps_d=5.8, mu=6.569384483107948,
             source="results_logs/all_trace_coexist_stick.out",
             critical_input_status="logged MC critical-line point"),
    ),
    "L-shaped": (
        dict(label="exact lattice-gas anchor", eps_nd=LATTICE_GAS_CRITICAL,
             eps_d=0.0, mu=2.0 * LATTICE_GAS_CRITICAL + math.log(4.0),
             source="exact 2D lattice-gas anchor",
             critical_input_status="exact anchor"),
        dict(label="weak directional", eps_nd=1.5134332013184795,
             eps_d=1.02, mu=4.9930143790043555,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC + FSS-checked"),
        dict(label="intermediate directional", eps_nd=1.3530862528281224,
             eps_d=1.8, mu=5.189030200916576,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC + FSS-checked"),
        dict(label="upper FSS-checked directional", eps_nd=1.2495060270045908,
             eps_d=2.6, mu=5.612505898686723,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC + FSS-checked"),
        dict(label="high directional", eps_nd=1.227554814851591,
             eps_d=2.8, mu=5.696611066056329,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=1.181526435952345,
             eps_d=3.2, mu=5.945036771232934,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=1.088309212923319,
             eps_d=3.66, mu=6.182178015338771,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=1.103771940125422,
             eps_d=4.18, mu=6.665537121424699,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=0.969690419981299,
             eps_d=5.56, mu=7.687096922196666,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC critical-line point"),
        dict(label="high directional", eps_nd=0.907398069529842,
             eps_d=5.8, mu=7.715814105273746,
             source="results_logs/all_trace_coexist_l.out",
             critical_input_status="logged MC critical-line point"),
    ),
}


@dataclass
class GrandStrip:
    model: PatchModel | None
    width: int
    periodic_y: bool
    states: np.ndarray
    n_column: np.ndarray
    nondirectional: np.ndarray
    directional: np.ndarray
    n_step: np.ndarray

    @classmethod
    def build(
        cls, model: PatchModel | None, width: int, periodic_y: bool = True
    ) -> "GrandStrip":
        """Build all column observables, with local state 0 denoting vacancy."""
        q = 1 if model is None else model.q
        states = np.asarray(
            list(itertools.product(range(q + 1), repeat=width)), dtype=np.int16
        )
        occupied = states > 0
        n_column = np.sum(occupied, axis=1).astype(np.int16)

        vertical_pairs = (
            tuple((j, (j + 1) % width) for j in range(width))
            if periodic_y
            else tuple((j, j + 1) for j in range(width - 1))
        )
        vertical_occ = np.asarray(
            [sum(int(row[j] and row[k]) for j, k in vertical_pairs)
             for row in occupied],
            dtype=np.int16,
        )
        horizontal_occ = np.sum(
            occupied[:, None, :] & occupied[None, :, :], axis=2
        )

        if model is None:
            vertical_dir = np.zeros(len(states), dtype=np.int16)
            horizontal_dir = np.zeros((len(states), len(states)), dtype=np.int16)
        else:
            north = np.asarray((0,) + model.north, dtype=np.int8)
            east = np.asarray((0,) + model.east, dtype=np.int8)
            south = np.asarray((0,) + model.south, dtype=np.int8)
            west = np.asarray((0,) + model.west, dtype=np.int8)
            vertical_dir = np.asarray(
                [sum(int(south[row[j]] and north[row[k]])
                     for j, k in vertical_pairs)
                 for row in states],
                dtype=np.int16,
            )
            horizontal_dir = np.sum(
                east[states[:, None, :]] * west[states[None, :, :]], axis=2
            ).astype(np.int16)

        nondirectional = horizontal_occ.astype(float) + 0.5 * (
            vertical_occ[:, None] + vertical_occ[None, :]
        )
        directional = horizontal_dir.astype(float) + 0.5 * (
            vertical_dir[:, None] + vertical_dir[None, :]
        )
        n_step = 0.5 * (n_column[:, None] + n_column[None, :])
        return cls(
            model=model,
            width=width,
            periodic_y=periodic_y,
            states=states,
            n_column=n_column,
            nondirectional=nondirectional,
            directional=directional,
            n_step=n_step,
        )

    @property
    def size(self) -> int:
        return len(self.states)

    def solve(self, eps_nd: float, eps_d: float, mu: float) -> dict[str, float]:
        """Solve the positive transfer matrix and all analytic derivatives."""
        exponent = (
            float(eps_nd) * self.nondirectional
            + float(eps_d) * self.directional
            - float(mu) * self.n_step
        )
        shift = float(np.max(exponent))
        transfer = np.exp(exponent - shift)
        values, left_vectors, right_vectors = eig(
            transfer, left=True, right=True, check_finite=False
        )
        index = int(np.argmax(values.real))
        lam_scaled = float(np.real(values[index]))
        if lam_scaled <= 0.0 or abs(np.imag(values[index])) > 1.0e-9:
            raise RuntimeError(f"invalid Perron root {values[index]}")
        left = np.real_if_close(left_vectors[:, index]).astype(float)
        right = np.real_if_close(right_vectors[:, index]).astype(float)
        if float(np.dot(left, right)) < 0.0:
            left = -left
        overlap = float(np.dot(left, right))
        denominator = lam_scaled * overlap

        def expectation(observable: np.ndarray) -> float:
            return float(
                np.dot(left, (observable * transfer) @ right) / denominator
            )

        contacts_column = expectation(self.nondirectional)
        directional_column = expectation(self.directional)
        particles_column = expectation(self.n_step)
        log_lambda = shift + math.log(lam_scaled)

        rho = particles_column / self.width
        contacts = contacts_column / self.width
        bonds = directional_column / self.width
        entropy = (
            log_lambda
            - eps_nd * contacts_column
            - eps_d * directional_column
            + mu * particles_column
        ) / self.width
        beta_u = -eps_nd * contacts - eps_d * bonds
        beta_f = -log_lambda / self.width - mu * rho
        identity_error = abs(entropy - (beta_u - beta_f))
        if identity_error > 2.0e-10:
            raise AssertionError("thermodynamic identity failed")

        # Stationary transfer-chain transition probabilities:
        # P_ij = T_ij r_j/(lambda r_i), pi_i = l_i r_i/(l.r).
        # Eigenvector signs are arbitrary but the Perron vectors are one-signed.
        if float(np.sum(right)) < 0.0:
            right = -right
        if float(np.sum(left)) < 0.0:
            left = -left
        stationary = left * right
        stationary /= float(np.sum(stationary))
        transition = (
            transfer * right[None, :] / (lam_scaled * right[:, None])
        )
        transition /= np.sum(transition, axis=1, keepdims=True)
        if np.min(transition) < -1.0e-13 or np.min(stationary) < -1.0e-13:
            raise AssertionError("invalid Perron Markov chain")

        log_transition = np.log(transition)
        entropy_rate_column = -float(
            np.sum(stationary[:, None] * transition * log_transition)
        )
        if abs(entropy_rate_column / self.width - entropy) > 3.0e-10:
            raise AssertionError("transfer-chain entropy rate mismatch")

        occupied = self.states > 0
        powers = (1 << np.arange(self.width, dtype=np.int64))
        occupancy_symbols = np.sum(occupied * powers[None, :], axis=1)
        n_symbols = 1 << self.width
        occupancy_probability = np.zeros((self.size, n_symbols), dtype=float)
        for symbol in range(n_symbols):
            occupancy_probability[:, symbol] = np.sum(
                transition[:, occupancy_symbols == symbol], axis=1
            )
        positive = occupancy_probability > 0.0
        occupancy_entropy_column = -float(
            np.sum(
                stationary[:, None]
                * np.where(
                    positive,
                    occupancy_probability
                    * np.log(np.where(positive, occupancy_probability, 1.0)),
                    0.0,
                )
            )
        )
        internal_entropy_column = entropy_rate_column - occupancy_entropy_column
        if internal_entropy_column < -3.0e-11:
            raise AssertionError("negative conditional internal entropy")
        internal_entropy_column = max(0.0, internal_entropy_column)
        internal_entropy_particle = internal_entropy_column / particles_column

        return {
            "log_lambda": log_lambda,
            "rho": rho,
            "contacts_per_site": contacts,
            "directional_bonds_per_site": bonds,
            "entropy_per_site": entropy,
            "beta_u_per_site": beta_u,
            "beta_f_per_site": beta_f,
            "occupancy_conditional_entropy_per_site": (
                occupancy_entropy_column / self.width
            ),
            "internal_conditional_entropy_per_site": (
                internal_entropy_column / self.width
            ),
            "internal_conditional_entropy_per_particle": (
                internal_entropy_particle
            ),
            "dloglambda_deps_nd": contacts_column,
            "dloglambda_deps_d": directional_column,
            "dloglambda_dmu": -particles_column,
        }


def direct_counts(
    strip: GrandStrip, left_index: int, right_index: int
) -> tuple[int, int, int, int, int]:
    """Independently recount column/edge observables with explicit loops."""
    left = strip.states[left_index]
    right = strip.states[right_index]
    n_left = sum(int(state > 0) for state in left)
    vertical_pairs = (
        tuple((j, (j + 1) % strip.width) for j in range(strip.width))
        if strip.periodic_y
        else tuple((j, j + 1) for j in range(strip.width - 1))
    )
    v_occ = sum(int(left[j] > 0 and left[k] > 0) for j, k in vertical_pairs)
    h_occ = sum(int(a > 0 and b > 0) for a, b in zip(left, right))
    if strip.model is None:
        return n_left, v_occ, h_occ, 0, 0
    model = strip.model
    north = (0,) + model.north
    east = (0,) + model.east
    south = (0,) + model.south
    west = (0,) + model.west
    v_dir = sum(int(south[left[j]] and north[left[k]])
                for j, k in vertical_pairs)
    h_dir = sum(int(east[a] and west[b]) for a, b in zip(left, right))
    return n_left, v_occ, h_occ, v_dir, h_dir


def validate_strip(strip: GrandStrip) -> list[str]:
    """Exhaustively check all state/edge counts and analytic derivatives."""
    for i in range(strip.size):
        n_i, v_occ_i, _, v_dir_i, _ = direct_counts(strip, i, i)
        if n_i != int(strip.n_column[i]):
            raise AssertionError("column occupancy mismatch")
        for j in range(strip.size):
            n_j, v_occ_j, h_occ, v_dir_j, h_dir = direct_counts(strip, j, i)
            # direct_counts(j,i) gives j as left and i as right.
            expected_nd = h_occ + 0.5 * (v_occ_j + v_occ_i)
            expected_d = h_dir + 0.5 * (v_dir_j + v_dir_i)
            if expected_nd != strip.nondirectional[j, i]:
                raise AssertionError("nondirectional count mismatch")
            if expected_d != strip.directional[j, i]:
                raise AssertionError("directional count mismatch")

    # Analytic derivatives from Perron vectors versus centered differences.
    a, d, mu = 1.31, 1.17, 4.63
    base = strip.solve(a, d, mu)
    delta = 1.0e-6
    checks = (
        ("eps_nd", (strip.solve(a + delta, d, mu)["log_lambda"]
                    - strip.solve(a - delta, d, mu)["log_lambda"])
         / (2.0 * delta), base["dloglambda_deps_nd"]),
        ("eps_d", (strip.solve(a, d + delta, mu)["log_lambda"]
                   - strip.solve(a, d - delta, mu)["log_lambda"])
         / (2.0 * delta), base["dloglambda_deps_d"]),
        ("mu", (strip.solve(a, d, mu + delta)["log_lambda"]
                - strip.solve(a, d, mu - delta)["log_lambda"])
         / (2.0 * delta), base["dloglambda_dmu"]),
    )
    messages = []
    for name, finite_difference, analytic in checks:
        error = abs(finite_difference - analytic)
        if error > 5.0e-7 * max(1.0, abs(analytic)):
            raise AssertionError(f"{name} derivative mismatch")
        messages.append(
            f"{('lattice-gas' if strip.model is None else strip.model.name):11s} "
            f"W={strip.width}: dlnlambda/d{name} FD error={error:.3e}"
        )
    return messages


def compare_point(
    model: PatchModel,
    width: int,
    full_strip: GrandStrip,
    point: dict[str, object],
) -> dict[str, object]:
    eps_nd = float(point["eps_nd"])
    eps_d = float(point["eps_d"])
    mu = float(point["mu"])
    full = full_strip.solve(eps_nd, eps_d, mu)
    s_internal_particle = full["internal_conditional_entropy_per_particle"]

    s_isolated = math.log(model.q)
    error_avg = abs(s_internal_particle)
    error_isolated = abs(s_isolated - s_internal_particle)

    return {
        "model": model.name,
        "W": width,
        "point_label": point["label"],
        "eps_nd": eps_nd,
        "eps_d": eps_d,
        "mu_critical_input": mu,
        "rho_exact_strip": full["rho"],
        "contacts_per_site_exact": full["contacts_per_site"],
        "directional_bonds_per_site_exact": full["directional_bonds_per_site"],
        "s_total_exact_per_site": full["entropy_per_site"],
        "s_occupancy_conditional_per_site": (
            full["occupancy_conditional_entropy_per_site"]
        ),
        "s_internal_conditional_per_site": (
            full["internal_conditional_entropy_per_site"]
        ),
        "s_internal_exact_per_particle": s_internal_particle,
        "s_internal_avgE_per_particle": 0.0,
        "s_internal_isolatedZ_per_particle": s_isolated,
        "abs_error_avgE": error_avg,
        "abs_error_isolatedZ": error_isolated,
        "closer_closure": "avgE" if error_avg < error_isolated else (
            "isolated-Z" if error_isolated < error_avg else "equal"
        ),
        "critical_input_status": point["critical_input_status"],
        "source": point["source"],
    }


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def interpolated_crossovers(
    full_strips: dict[tuple[str, int], GrandStrip]
) -> list[dict[str, object]]:
    """Find switches along piecewise-linear interpolation of logged triples."""
    rows: list[dict[str, object]] = []
    for model in MODELS:
        points = CRITICAL_POINTS[model.name]
        target = 0.5 * math.log(model.q)
        for width in (3, 4):
            strip = full_strips[(model.name, width)]
            found: dict[str, object] | None = None
            for left, right in zip(points[:-1], points[1:]):
                d0, d1 = float(left["eps_d"]), float(right["eps_d"])

                def parameters(eps_d: float) -> tuple[float, float]:
                    fraction = (eps_d - d0) / (d1 - d0)
                    eps_nd = float(left["eps_nd"]) + fraction * (
                        float(right["eps_nd"]) - float(left["eps_nd"])
                    )
                    mu = float(left["mu"]) + fraction * (
                        float(right["mu"]) - float(left["mu"])
                    )
                    return eps_nd, mu

                def residual(eps_d: float) -> float:
                    eps_nd, mu = parameters(eps_d)
                    return (
                        strip.solve(eps_nd, eps_d, mu)[
                            "internal_conditional_entropy_per_particle"
                        ]
                        - target
                    )

                f0, f1 = residual(d0), residual(d1)
                if f0 == 0.0 or f0 * f1 <= 0.0:
                    root = d0 if f0 == 0.0 else float(
                        brentq(residual, d0, d1, xtol=2.0e-12)
                    )
                    eps_nd_root, mu_root = parameters(root)
                    bracket_statuses = {
                        str(left["critical_input_status"]),
                        str(right["critical_input_status"]),
                    }
                    if bracket_statuses <= {
                        "exact anchor", "logged MC + FSS-checked"
                    }:
                        status = "interpolation between FSS-checked logged points"
                    else:
                        status = "interpolation between logged MC critical-line points"
                    found = {
                        "model": model.name,
                        "W": width,
                        "target_entropy_per_particle": target,
                        "eps_d_crossover": root,
                        "eps_nd_interpolated": eps_nd_root,
                        "mu_interpolated": mu_root,
                        "bracket_eps_d_low": d0,
                        "bracket_eps_d_high": d1,
                        "status": status,
                    }
                    break
            if found is None:
                found = {
                    "model": model.name,
                    "W": width,
                    "target_entropy_per_particle": target,
                    "eps_d_crossover": "not reached",
                    "eps_nd_interpolated": "",
                    "mu_interpolated": "",
                    "bracket_eps_d_low": "",
                    "bracket_eps_d_high": "",
                    "status": f"not reached through eps_d={float(points[-1]['eps_d']):.2f}",
                }
            rows.append(found)
    return rows


def make_plot(rows: list[dict[str, object]], output_dir: Path) -> None:
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 9.5,
            "axes.labelsize": 10.5,
            "axes.titlesize": 11,
            "legend.fontsize": 8.5,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "axes.linewidth": 0.8,
            "pdf.fonttype": 42,
        }
    )
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.25))
    colors = {3: "#0072B2", 4: "#D55E00"}
    markers = {3: "o", 4: "s"}
    for ax, model, panel in zip(axes, MODELS, ("a", "b")):
        selected = [row for row in rows if row["model"] == model.name]
        for width in (3, 4):
            group = [row for row in selected if row["W"] == width]
            group.sort(key=lambda row: float(row["eps_d"]))
            ax.plot(
                [float(row["eps_d"]) for row in group],
                [float(row["s_internal_exact_per_particle"])
                 for row in group],
                color=colors[width], marker=markers[width], linewidth=1.7,
                markersize=5.0, label=rf"exact $W={width}$",
            )
        ax.axhline(0.0, color="0.25", linestyle=(0, (5, 2)), linewidth=1.1,
                   label="avgE")
        ax.axhline(math.log(model.q), color="0.5", linestyle=(0, (2, 2)),
                   linewidth=1.2, label=r"isolated-$Z$")
        ax.axhline(0.5 * math.log(model.q), color="0.7", linestyle=":",
                   linewidth=0.9, label="equal error")
        ax.set_title(f"({panel}) {model.name.capitalize()}")
        ax.set_xlabel(r"critical-line input $\beta\varepsilon_{\mathrm{d}}$")
        ax.set_ylabel(r"effective internal $s/k_{\mathrm{B}}$ per particle")
        ax.set_ylim(-0.04, math.log(model.q) + 0.08)
        ax.grid(color="0.9", linewidth=0.6)
        ax.tick_params(direction="in", top=True, right=True)
        ax.legend(frameon=False, loc="best", handlelength=2.4)
    fig.tight_layout(w_pad=1.8)
    fig.savefig(output_dir / "critical_point_closure_comparison.pdf",
                bbox_inches="tight")
    fig.savefig(output_dir / "critical_point_closure_comparison.png",
                dpi=500, bbox_inches="tight")
    plt.close(fig)


def write_report(
    path: Path,
    rows: list[dict[str, object]],
    crossover_rows: list[dict[str, object]],
) -> None:
    lines = [
        "# Exact strip comparison at representative critical points",
        "",
        "## What is being compared",
        "",
        "The original fully occupied strip cannot test the nondirectional",
        "interaction because every nearest-neighbor pair is then occupied. Here",
        "each site can instead be vacant or carry one of q orientations. The",
        "critical-point benchmark uses a periodic transverse boundary (an infinite",
        "cylinder) so that every site retains the bulk coordination number four;",
        "the earlier open-strip entropy calculation is not altered. For",
        "neighboring occupied sites the energy is `-eps_nd`, with an additional",
        "`-eps_d` for a correctly aligned directional bond. The positive logged",
        "`mu` is the manuscript simulation's occupancy cost.",
        "",
        "For a column C with particle number n(C), occupied-contact count a_v(C),",
        "and directional-bond count d_v(C), the exact grand-canonical matrix is",
        "",
        "`T_CC' = exp{ eps_nd[A_h+(A_v(C)+A_v(C'))/2]",
        "              + eps_d[D_h+(D_v(C)+D_v(C'))/2]",
        "              - mu[n(C)+n(C')]/2 }`.",
        "",
        "Finite-width strips have no true phase transition. The tabulated values",
        "are exact strip thermodynamics evaluated at representative 2D critical",
        "triples from the project logs, not newly claimed strip critical points.",
        "The sparse extension reaches eps_d=5.8 using successful points from",
        "the original Monte Carlo critical-line continuation. A lower-coupling",
        "subset was additionally examined in a later finite-size-scaling campaign;",
        "the lack of that same secondary check at every higher-coupling point is",
        "not a failure of the original MC calculation and no point is excluded",
        "from the present transfer-matrix comparison.",
        "",
        "The Perron vectors define the exact stationary column Markov chain",
        "`P(C'|C)=T_CC' r_C'/(lambda r_C)`. Writing a new column as its occupancy",
        "pattern O' plus its occupied-site orientations R' gives the exact",
        "nonnegative decomposition `H(C'|C)=H(O'|C)+H(R'|C,O')`. We use",
        "`s_int=H(R'|C,O')/<N'>` as the environment-conditioned internal entropy",
        "per occupied particle. avgE sets this term to zero and isolated-Z sets it",
        "to ln(q). This conditional definition avoids subtracting an unrelated",
        "reference entropy and includes both nondirectional and directional",
        "interactions in the exact Gibbs weights.",
        "",
        "## Numerical comparison",
        "",
        "| model | W | eps_nd | eps_d | rho | exact s_int | avgE error | isolated-Z error | closer | input status |",
        "|:--|--:|--:|--:|--:|--:|--:|--:|:--|:--|",
    ]
    for row in rows:
        lines.append(
            f"| {row['model']} | {row['W']} | {float(row['eps_nd']):.6f} | "
            f"{float(row['eps_d']):.2f} | {float(row['rho_exact_strip']):.6f} | "
            f"{float(row['s_internal_exact_per_particle']):.6f} | "
            f"{float(row['abs_error_avgE']):.6f} | "
            f"{float(row['abs_error_isolatedZ']):.6f} | "
            f"{row['closer_closure']} | {row['critical_input_status']} |"
        )
    lines.extend(
        [
            "",
            "## Closure switch along the sampled critical line",
            "",
            "The following values use piecewise-linear interpolation of eps_nd and",
            "mu between adjacent critical-input triples; they are interpolation",
            "diagnostics, not additional Monte Carlo critical points.",
            "",
            "| model | W | eps_d at equal error | status |",
            "|:--|--:|--:|:--|",
        ]
    )
    for row in crossover_rows:
        value = row["eps_d_crossover"]
        rendered = value if isinstance(value, str) else f"{float(value):.6f}"
        lines.append(
            f"| {row['model']} | {row['W']} | {rendered} | {row['status']} |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "At eps_d=0 the calculation recovers s_int=ln(q) to numerical",
            "precision, so isolated-Z is exact in the genuinely isolated-orientation",
            "limit. Directional bonding lowers the environment-conditioned internal",
            "entropy below ln(q). The table determines, point by point, whether that",
            "loss is large enough to make the zero-entropy avgE limit closer than the",
            "full isolated degeneracy.",
            "",
            "For stick, the closure switch occurs in the lower-coupling subset that",
            "also received the secondary FSS check. For L-shaped particles, the",
            "switch occurs at higher coupling and depends more strongly on strip",
            "width; this is a finite-width convergence issue in the exact-strip",
            "benchmark, not evidence that the underlying MC points failed.",
            "",
            "This is a controlled exact-strip benchmark of the entropy closure. It",
            "does not replace the full SAFT-P critical-line recomputation because the",
            "finite strip has no critical singularity and the SAFT-P plaquette classes",
            "contain additional coarse-grained variables.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir", type=Path,
        default=Path(__file__).resolve().parent / "critical_points",
    )
    args = parser.parse_args()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    full_strips = {
        (model.name, width): GrandStrip.build(model, width)
        for model in MODELS for width in (3, 4)
    }
    validation: list[str] = []
    for strip in full_strips.values():
        validation.extend(validate_strip(strip))

    rows: list[dict[str, object]] = []
    for model in MODELS:
        for point in CRITICAL_POINTS[model.name]:
            for width in (3, 4):
                rows.append(
                    compare_point(
                        model,
                        width,
                        full_strips[(model.name, width)],
                        point,
                    )
                )

    crossover_rows = interpolated_crossovers(full_strips)
    # At eps_d=0, occupied-site orientations are independent and uniform.
    for row in rows:
        if float(row["eps_d"]) == 0.0:
            expected = math.log(2 if row["model"] == "stick" else 4)
            error = abs(float(row["s_internal_exact_per_particle"]) - expected)
            if error > 2.0e-10:
                raise AssertionError("eps_d=0 isolated-degeneracy check failed")
            validation.append(
                f"{row['model']:8s} W={row['W']}: eps_d=0, "
                f"|s_int-ln(q)|={error:.3e}"
            )

    write_csv(output_dir / "critical_point_closure_comparison.csv", rows)
    write_csv(output_dir / "critical_line_interpolated_crossovers.csv", crossover_rows)
    (output_dir / "validation_summary.txt").write_text(
        "\n".join(validation) + "\n", encoding="utf-8"
    )
    write_report(
        output_dir / "critical_point_closure_comparison.md", rows, crossover_rows
    )
    make_plot(rows, output_dir)
    print("\n".join(validation))
    print(f"Wrote critical-point comparison to {output_dir}")


if __name__ == "__main__":
    main()
