"""
mc_line_core.py -- finite-size critical *line* for stick / L-shaped patchy
particles on the square lattice.

Purpose
-------
Run the continuation sweep of notebooks/mc_sims_{l,stick}_shaped.ipynb --
i.e. `main(eps_ns, eps_sp_prev, mu)`, which traces the critical line
eps_nd,c(eps_d) by stepping eps_d and re-locating criticality at every step --
at several lattice sizes (L = 10, 20, 30), so that the whole line can be
extrapolated to the thermodynamic limit rather than a single state point.

Relation to the rest of src/
----------------------------
  mc_fss_core.py   one point, eps_d FIXED, anchored on the logged L=10 trace.
                   Answers "how far does eps_nd,c move with L at eps_d=1.96?"
  mc_line_core.py  (this file) the notebook's DIFFERENTIAL continuation, run
                   at several L.  Answers "how far does the whole line move?"

The estimator is the notebook's, function for function:

    equal-area mu search by simulation
      -> mu* refined by histogram reweighting in mu
      -> mixed-field (s, r) fit of  M = rho - s*u  against the 2D-Ising
         universal order-parameter distribution P*(x)
      -> joint (eps_nd, mu) reweighting from eps_d_prev to eps_d, minimising
         the Jensen-Shannon divergence to P*(x)

Those functions are carried over verbatim (they are byte-identical to the ones
in mc_fss_core.py, which were themselves lifted from the notebook).  This file
is deliberately self-contained: it imports only simulate_functions_min, so the
line campaign cannot be broken by an edit to the fixed-eps_d campaign.

What changed relative to the notebook cell
------------------------------------------
 1. L is a parameter.  Chain length, snapshot interval and acceptance-block
    size all scale with it:

        steps(L) = sweeps_ref * (L/L_ref)^z * L^2 ,   z = 2.17

    z is the dynamic exponent for local single-site dynamics in the 2D Ising
    universality class; sweeps_ref = 6e6 at L_ref = 10 reproduces the
    notebook's 600_000_000 attempts.  L=10/20/30 -> 6.0e8 / 1.08e10 / 5.9e10.

 2. MC replicas run in parallel worker processes.  The notebook ran its 5
    replicas sequentially inside build_data_mu_cpu.

 3. The numba RNG is seeded per worker.  numba's np.random state is
    process-global and is INHERITED ACROSS fork(); np.random.seed() from
    python does not touch it.  Without an explicit @njit reseed every replica
    in a forked pool reproduces the identical Markov chain, and the error bars
    look perfectly healthy while carrying no information.

 4. block_size scales with the chain.  simulate_lattice_numba allocates
    simulation_steps//block_size float64s for the acceptance trace; at the
    notebook's block_size=1000 and L=30's 5.9e10 steps that is ~470 MB per
    replica.

 5. The equal-area mu scout runs on SHORT chains (scout_frac of full length)
    and the production chain is then run once at the located mu.  The notebook
    used full-length chains inside find_mu_equal_areas_by_simulation and reused
    the last one as the production data; at L=30 that multiplies the cost of
    every continuation step by the scout's iteration count.  Set
    --scout-frac 1.0 to recover the notebook's behaviour exactly.

 6. The sweep is cut into segments so it can be spread over a SLURM array, and
    each segment checkpoints after every eps_d step so it can be chained across
    walltime limits.

 7. The 2D-Ising reference P*(x) is generated by a numba Wolff sampler and
    cached to disk, so every task in the campaign fits against a bit-identical
    reference instead of redrawing it (and adding noise) per call.

 8. Every raw sample (rho, u, C_ns, C_sp, N_mu) at the final pass of each step
    is optionally archived, so the mixed-field analysis can be redone offline.

 9. L-BFGS-B stalls are detected and flagged.  The notebook's
    optimize_eps_mu_Mc_fixed_epsA_fixed_s minimises over a digitised histogram,
    so the objective is piecewise constant and the finite-difference gradient
    is noise.  In continuation mode this is usually harmless -- each step
    starts displaced by d(eps_d) on the steep flank -- but not always: the
    logged bent-geometry trace has runs of 3-4 consecutive steps with eps_nd
    frozen to 5 decimals.  Every step now records `stalled`, and
    --scan-fallback re-does the stalled ones with a grid scan of the same
    objective.

Sign conventions are inherited unchanged from the notebook and are internally
consistent with the MC kernel in simulate_functions_min.py (which minimises
Phi = E_bonds + sum_k mu[s_k], i.e. `mu` enters as an occupancy penalty).  They
are deliberately NOT "corrected" here: the published L=10 line comes out of
this exact code path and the finite-size displacement is a difference taken at
fixed convention.

Naming: the notebook calls the two couplings (eps_ns, eps_sp); the manuscript
calls them (eps_nd, eps_d).  They are the same two numbers.  This file uses the
notebook names internally and the manuscript names in output columns.
"""

from __future__ import annotations

import json
import math
import os
import sys
import time
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import numba as nb
from scipy.optimize import minimize

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from simulate_functions_min import (  # noqa: E402
    simulate_lattice_numba,
    get_species_list_ind,
)

# numpy 2 renamed trapz -> trapezoid; keep both working.
_trapz = getattr(np, "trapezoid", None) or np.trapz

# Bumped whenever a change alters the NUMBERS a run produces, so a stale
# checkout cannot masquerade as a fresh result.  Stamped into every .npz.
#   1  first cluster port
#   2  relocation mode at fixed eps_d (grid scan, not L-BFGS-B)
#   3  mixed-field fit confined to the physical branch of s; s diagnostics
#      stored; unidentifiable-s detection
#   4  relocation window widened and no longer scaled down with L (it was
#      shrinking faster than the displacement it measures); the scan now masks
#      by ESS/n before choosing a minimum, which is what makes a wide window
#      safe, and "no interior minimum" is judged on the admissible region
#   5  relocation also stores C_ns, C_sp, N_mu and the exact theta_ref /
#      theta_star, so the JS comparison the objective actually performs can be
#      reconstructed offline and overlaid on the Ising reference
#   6  the relocation scan now sets mu by EQUAL AREA at each eps_nd instead of
#      profiling it freely.  Letting JS choose mu left the located point off
#      coexistence: measured at eps_d=1.8, basin masses were 0.503/0.497 at
#      L=10 but 0.525/0.475 at L=20, and because the standardised variable has
#      zero mean by construction, p_L*|c_L| = p_R*|c_R| exactly -- so a mass
#      imbalance ALONE pushes the lighter peak outward.  That accounted for the
#      whole 0.096 dense-peak displacement at L=20.  Same fix mc_fss made
#      (FINDINGS 4.2, equal_area_mu_at_eps).
MC_LINE_VERSION = 6

# Results from this version onward are directly comparable.  Version 3 fixed
# the mixed-field fit (the change that made eps_nd,c meaningful at all); its
# numbers are trustworthy but were located in a narrower window, so v3 and v4
# rows must not be mixed inside one table.
MC_LINE_MIN_TRUSTED = 3

__all__ = [
    "MC_LINE_VERSION",
    "SYSTEMS",
    "SweepConfig",
    "run_segment",
    "ising_reference",
    "numba_seed",
    "make_lattices",
    "run_ref_once_mu",
    "lattice_gas_anchor",
]


# ----------------------------------------------------------------------------
# systems
# ----------------------------------------------------------------------------
# species strings are exactly those used in the two manuscript notebooks.
SYSTEMS = {
    # mc_sims_stick_shaped.ipynb :  get_species_list_ind(['A0A0','SSSS'])
    #   -> 2 collinear orientations + 1 vacancy/solvent species
    "stick": dict(species=["A0A0", "SSSS"], n_orient=2),
    # mc_sims_l_shaped.ipynb     :  get_species_list_ind(['AA','SSSS'])
    #   -> 4 bent orientations + 1 vacancy/solvent species
    "l": dict(species=["AA", "SSSS"], n_orient=4),
}


def lattice_gas_anchor(system):
    """Exact critical point at eps_d = 0.

    At eps_d = 0 every particle-particle contact carries -eps_nd regardless of
    patch identity, so the model reduces to the plain 2D lattice gas:

        eps_nd,c = 2 ln(1 + sqrt 2) = 1.762747      mu_c = 2 eps_nd,c + ln g

    with g the number of distinguishable orientations (2 stick, 4 L).  This is
    where the notebook's first cell starts.  Note the notebook used ln 4 for
    both geometries; ln g is the correct generalisation and matters only for
    the stick system.
    """
    g = SYSTEMS[system]["n_orient"]
    eps_nd = 2.0 * math.log(1.0 + math.sqrt(2.0))
    return float(eps_nd), float(2.0 * eps_nd + math.log(g))


# ----------------------------------------------------------------------------
# RNG seeding for the numba kernel
# ----------------------------------------------------------------------------
@nb.njit(cache=True)
def numba_seed(s):
    """Seed numba's internal np.random state.

    np.random.seed() called from *python* does not touch the state used inside
    njit code, and that state is inherited across fork().  Every worker process
    must call this with a distinct value or the replicas are not independent.
    """
    np.random.seed(s)
    return np.random.randint(0, 1 << 30)


# ----------------------------------------------------------------------------
# 2D Ising reference distribution P*(x)  (numba Wolff, cached)
# ----------------------------------------------------------------------------
@nb.njit(cache=True)
def _wolff_magnetisations(L, p_add, burnin, nsamples, seed):
    np.random.seed(seed)
    N = L * L
    spins = np.empty((L, L), dtype=np.int8)
    for i in range(L):
        for j in range(L):
            spins[i, j] = 1 if np.random.random() < 0.5 else -1

    stack_i = np.empty(N, dtype=np.int32)
    stack_j = np.empty(N, dtype=np.int32)
    in_cluster = np.zeros((L, L), dtype=np.bool_)
    touched_i = np.empty(N, dtype=np.int32)
    touched_j = np.empty(N, dtype=np.int32)

    out = np.empty(nsamples, dtype=np.float64)

    for it in range(burnin + nsamples):
        x = np.random.randint(0, L)
        y = np.random.randint(0, L)
        target = spins[x, y]

        ntouch = 0
        sp = 0
        stack_i[sp] = x
        stack_j[sp] = y
        sp += 1
        in_cluster[x, y] = True
        touched_i[ntouch] = x
        touched_j[ntouch] = y
        ntouch += 1

        while sp > 0:
            sp -= 1
            i = stack_i[sp]
            j = stack_j[sp]
            for d in range(4):
                if d == 0:
                    ni = i
                    nj = (j + 1) % L
                elif d == 1:
                    ni = i
                    nj = (j - 1) % L
                elif d == 2:
                    ni = (i + 1) % L
                    nj = j
                else:
                    ni = (i - 1) % L
                    nj = j
                if (not in_cluster[ni, nj]) and spins[ni, nj] == target:
                    if np.random.random() < p_add:
                        in_cluster[ni, nj] = True
                        stack_i[sp] = ni
                        stack_j[sp] = nj
                        sp += 1
                        touched_i[ntouch] = ni
                        touched_j[ntouch] = nj
                        ntouch += 1

        for t in range(ntouch):
            spins[touched_i[t], touched_j[t]] *= -1
            in_cluster[touched_i[t], touched_j[t]] = False

        if it >= burnin:
            m = 0
            for i in range(L):
                for j in range(L):
                    m += spins[i, j]
            out[it - burnin] = m / N

    return out


def smooth_histogram_gaussian(x_centers, p_hist, sigma=1.0):
    """Verbatim from the manuscript notebooks."""
    x_centers = np.asarray(x_centers, float)
    p_hist = np.asarray(p_hist, float)
    dx = float(np.mean(np.diff(x_centers)))
    if not np.allclose(np.diff(x_centers), dx, rtol=1e-4, atol=1e-8):
        raise ValueError("x_centers must be uniformly spaced.")
    sigma_bins = sigma / dx
    halfw = int(np.ceil(4 * sigma_bins))
    kx = np.arange(-halfw, halfw + 1, dtype=float)
    K = np.exp(-0.5 * (kx / sigma_bins) ** 2)
    K /= K.sum()
    p_pad = np.pad(p_hist, (halfw, halfw), mode="reflect")
    p_conv = np.convolve(p_pad, K, mode="same")[halfw:-halfw]
    p_conv /= _trapz(p_conv, x_centers)
    return x_centers, p_conv


def ising_reference(cache_path=None, L_ising=64, burnin=3000,
                    nsamples=20000, seed=20260814, nbins=101, n_pad=6,
                    smooth_sigma=0.05, verbose=True):
    """Universal 2D-Ising order-parameter distribution P*(x), unit variance.

    Same construction as the notebooks (L=64 Wolff at Tc, 3000 burn-in
    clusters, 20000 samples, 101 bins + 6 zero-padding bins per side, Gaussian
    smoothing sigma=0.05), but with a fixed seed and an on-disk cache, so that
    every task in the campaign fits against a bit-identical reference.

    The cache is shared with mc_fss_core.ising_reference -- same defaults, same
    seed, same file layout -- so the two campaigns are directly comparable.
    """
    if cache_path is not None and os.path.exists(cache_path):
        z = np.load(cache_path)
        return z["centers"], z["edges"], z["P_smooth"]

    Tc = 2.0 / math.log(1.0 + math.sqrt(2.0))
    p_add = 1.0 - math.exp(-2.0 / Tc)
    if verbose:
        print(f"[ising-ref] Wolff L={L_ising} Tc={Tc:.6f} "
              f"burnin={burnin} samples={nsamples} seed={seed}", flush=True)

    m = _wolff_magnetisations(int(L_ising), float(p_add), int(burnin),
                              int(nsamples), int(seed))

    m_mean = float(m.mean())
    m_std = float(m.std(ddof=1))
    x_samples = (m - m_mean) / m_std

    R_data = float(np.max(np.abs(x_samples)))
    dx = 2.0 * R_data / nbins
    R = R_data + n_pad * dx
    edges = np.linspace(-R, R, (nbins + 2 * n_pad) + 1)
    hist, _ = np.histogram(x_samples, bins=edges, density=True)
    centers = 0.5 * (edges[:-1] + edges[1:])

    centers, P_smooth = smooth_histogram_gaussian(centers, hist,
                                                  sigma=smooth_sigma)
    P_smooth = P_smooth / _trapz(P_smooth, centers)

    if cache_path is not None:
        os.makedirs(os.path.dirname(os.path.abspath(cache_path)), exist_ok=True)
        np.savez_compressed(cache_path, centers=centers, edges=edges,
                            P_smooth=P_smooth, L_ising=L_ising, seed=seed,
                            nsamples=nsamples, burnin=burnin)
        if verbose:
            print(f"[ising-ref] cached -> {cache_path}", flush=True)

    return centers, edges, P_smooth


# ----------------------------------------------------------------------------
# data container  (verbatim from the notebooks, plus per-replica diagnostics)
# ----------------------------------------------------------------------------
class ReweightDataMU:
    def __init__(self, beta, L, N_sites, eps_ns0, eps_sp0, mu0,
                 N_mu, rho_mu, rho_total, u, C_ns, C_sp, diag=None):
        self.beta = float(beta)
        self.L = int(L)
        self.N_sites = int(N_sites)
        self.eps_ns0 = float(eps_ns0)
        self.eps_sp0 = float(eps_sp0)
        self.mu0 = float(mu0)
        self.N_mu = np.asarray(N_mu, float).ravel()
        self.rho_mu = np.asarray(rho_mu, float).ravel()
        self.rho_total = np.asarray(rho_total, float).ravel()
        self.u = np.asarray(u, float).ravel()
        self.C_ns = np.asarray(C_ns, float).ravel()
        self.C_sp = np.asarray(C_sp, float).ravel()
        self.diag = diag or {}
        n = len(self.N_mu)
        assert all(len(getattr(self, k)) == n
                   for k in ("rho_mu", "rho_total", "u", "C_ns", "C_sp")), \
            "ReweightDataMU: array length mismatch"


def to_int_lattice(lat):
    lat = np.asarray(lat)
    if np.issubdtype(lat.dtype, np.integer):
        return lat.astype(np.int64, copy=False)
    return np.vectorize(lambda p: p.index, otypes=[np.int64])(lat)


# ----------------------------------------------------------------------------
# single replica
# ----------------------------------------------------------------------------
def run_ref_once_mu(lattice0, species, species_mu_indices,
                    eps_ns0, eps_sp0, mu0, *,
                    steps, snapshot_interval, buffer_size, block_size,
                    empty_index=-1, beta=1.0, keep_final=False):
    """One MC replica at (eps_ns0, eps_sp0, mu0).  Same J_patch as the notebooks."""
    lattice_int = to_int_lattice(lattice0)

    def J_patch(epsp, epsn):
        return np.array([[-epsn, -epsn, 0.0],
                         [-epsn, -epsn - epsp, 0.0],
                         [0.0, 0.0, 0.0]], float)

    Jref = J_patch(float(eps_sp0), float(eps_ns0))
    patches_by_species = np.asarray([getattr(s, "patches") for s in species],
                                    dtype=np.uint8)

    n_species = len(species)
    if empty_index < 0:
        empty_index = n_species - 1
    empty_index = int(empty_index)

    mu_table = np.zeros(n_species, dtype=np.float64)
    idx = np.unique(np.asarray(species_mu_indices, dtype=np.int64))
    idx = idx[(idx >= 0) & (idx < n_species)]
    mu_table[idx] = float(mu0)

    snap_counts, energies, densities, lat_final = simulate_lattice_numba(
        lattice_int,
        Jref,
        patches_by_species,
        mu_table,
        empty_index=empty_index,
        eps_ns0=float(eps_ns0),
        eps_sp0=float(eps_sp0),
        simulation_steps=int(steps),
        beta=float(beta),
        snapshot_interval=int(snapshot_interval),
        buffer_size=int(buffer_size),
        block_size=int(block_size),
        species_mu_indices=idx,
    )

    snap_counts = dict(snap_counts)
    N_sites = int(snap_counts["N_sites"])
    if "rho_mu" not in snap_counts or "N_mu" not in snap_counts:
        dens = np.asarray(densities, float)
        rho_mu = dens[:, idx].sum(axis=1) if idx.size else np.zeros(dens.shape[0])
        snap_counts["rho_mu"] = rho_mu
        snap_counts["N_mu"] = rho_mu * float(N_sites)

    for k in ["N_mu", "rho_mu", "Nocc_total", "rho_total", "u", "C_ns", "C_sp"]:
        if k in snap_counts:
            snap_counts[k] = np.asarray(snap_counts[k], float).ravel()

    if keep_final:
        snap_counts["lat_final"] = np.asarray(lat_final, dtype=np.int8)
    return snap_counts


# --- worker plumbing --------------------------------------------------------
_W = {}


def _worker_init(payload, base_seed):
    """Fork/spawn initialiser: pin threads, seed numba, cache static arrays."""
    for v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS",
              "NUMEXPR_NUM_THREADS", "NUMBA_NUM_THREADS"):
        os.environ[v] = "1"
    pid_tag = os.getpid() & 0xFFFF
    seed = (int(base_seed) * 1_000_003 + pid_tag) % (2 ** 31 - 1)
    numba_seed(seed)
    np.random.seed(seed)
    _W.update(payload)
    _W["seed"] = seed


def _worker_run(args):
    (rep, call, lat, eps_ns, eps_sp, mu, steps, snap, buf, block) = args
    # Distinct stream per (replica, simulate() call).  Without the `call` term
    # every simulate() call inside one continuation step would restart the same
    # chain from the same state, and the scout would keep re-measuring it.
    numba_seed((_W["seed"] + 7919 * (rep + 1) + 104729 * (call + 1))
               % (2 ** 31 - 1))
    out = run_ref_once_mu(
        lat, _W["species"], _W["species_mu_indices"],
        eps_ns, eps_sp, mu,
        steps=steps, snapshot_interval=snap, buffer_size=buf,
        block_size=block, empty_index=_W["empty_index"], beta=_W["beta"],
    )
    keep = ["N_mu", "rho_mu", "Nocc_total", "rho_total", "u", "C_ns", "C_sp"]
    slim = {k: out[k] for k in keep}
    slim["N_sites"] = out["N_sites"]
    slim["accept_rate"] = out["accept_rate"]
    slim["rep"] = rep
    return slim


def _tunnelling_stats(rho, lo=0.4, hi=0.6):
    """Number of dilute<->dense round trips in a raw (unshuffled) trace.

    `crossings == 0` for any replica means that point is not ergodic on the
    chain length used, and the located critical point should not be trusted.
    """
    rho = np.asarray(rho, float)
    state = np.zeros(rho.size, dtype=np.int8)
    state[rho <= lo] = -1
    state[rho >= hi] = +1
    nz = state[state != 0]
    if nz.size == 0:
        return dict(crossings=0, frac_dilute=0.0, frac_dense=0.0,
                    frac_middle=1.0)
    crossings = int(np.sum(nz[1:] != nz[:-1]))
    return dict(
        crossings=crossings,
        frac_dilute=float(np.mean(rho <= lo)),
        frac_dense=float(np.mean(rho >= hi)),
        frac_middle=float(np.mean((rho > lo) & (rho < hi))),
    )


def build_data_mu(pool, lattices, species, species_mu_indices,
                  eps_ns, eps_sp, mu, beta,
                  steps, snapshot_interval, buffer_size, block_size,
                  n_replicas, burn_frac, rng_shuffle, L, call_id=0,
                  keep_raw=False):
    """Parallel replacement for the notebook's build_data_mu_cpu."""
    jobs = []
    for r in range(int(n_replicas)):
        lat = lattices[r % len(lattices)].copy()
        jobs.append((r, int(call_id), lat, float(eps_ns), float(eps_sp),
                     float(mu), int(steps), int(snapshot_interval),
                     int(buffer_size), int(block_size)))

    runs = list(pool.map(_worker_run, jobs)) if pool is not None \
        else [_worker_run(j) for j in jobs]
    runs.sort(key=lambda d: d["rep"])

    keys = ["N_mu", "rho_mu", "Nocc_total", "rho_total", "u", "C_ns", "C_sp"]

    per_rep = []
    trimmed = []
    for r in runs:
        n = r["rho_mu"].size
        b = int(np.floor(burn_frac * n))
        st = _tunnelling_stats(r["rho_mu"][b:])
        st["rep"] = r["rep"]
        st["accept_rate"] = r["accept_rate"]
        st["mean_rho"] = float(np.mean(r["rho_mu"][b:]))
        st["n_samples"] = int(n - b)
        per_rep.append(st)
        trimmed.append({k: r[k][b:] for k in keys})

    cat = {k: np.concatenate([t[k] for t in trimmed]) for k in keys}
    raw = {k: cat[k].copy() for k in keys} if keep_raw else {}

    idx = rng_shuffle.permutation(len(cat["Nocc_total"]))
    for k in keys:
        cat[k] = cat[k][idx]

    N_sites = int(runs[0]["N_sites"])

    diag = dict(
        per_replica=per_rep,
        total_crossings=int(sum(p["crossings"] for p in per_rep)),
        min_crossings=int(min(p["crossings"] for p in per_rep)),
        mean_accept=float(np.mean([p["accept_rate"] for p in per_rep])),
        rho_spread=float(np.max([p["mean_rho"] for p in per_rep])
                         - np.min([p["mean_rho"] for p in per_rep])),
        raw=raw,
    )

    return ReweightDataMU(
        beta=beta, L=L, N_sites=N_sites,
        eps_ns0=eps_ns, eps_sp0=eps_sp, mu0=mu,
        N_mu=cat["N_mu"], rho_mu=cat["rho_mu"], rho_total=cat["rho_total"],
        u=cat["u"], C_ns=cat["C_ns"], C_sp=cat["C_sp"], diag=diag,
    )


# ----------------------------------------------------------------------------
# reweighting / mixed-field machinery  (verbatim from the notebooks)
# ----------------------------------------------------------------------------
def _ess(w):
    w = np.asarray(w, float)
    s1 = w.sum()
    s2 = (w * w).sum()
    return (s1 * s1) / max(s2, 1e-300)


def _weights_mu(N_counts, mu_new, mu_ref, beta=1.0, clip=700.0):
    dmu = float(mu_new - mu_ref)
    logw = -beta * dmu * np.asarray(N_counts, float)
    logw -= np.max(logw)
    logw = np.clip(logw, -clip, None)
    return np.exp(logw)


def _rho_hist_density(rho, w, edges):
    counts, _ = np.histogram(rho, bins=edges, weights=w, density=False)
    W = counts.sum()
    p = counts / max(W, 1e-300)
    width = np.diff(edges)
    dens = p / width
    centers = 0.5 * (edges[:-1] + edges[1:])
    return centers, dens


def _area_in_window(edges, dens, lo, hi):
    lo = float(lo)
    hi = float(hi)
    Le = edges[:-1]
    Re = edges[1:]
    overlap = np.maximum(0.0, np.minimum(Re, hi) - np.maximum(Le, lo))
    return float(np.sum(dens * overlap))


def equal_peak_mu_in_rho_by_reweighting(
    rho, N_counts, mu_ref, *,
    beta=1.0,
    rho_edges=None, rho_bins=200,
    dilute_window=(0.0, 0.3),
    dense_window=(0.7, 1.0),
    ess_min=2_000,
    mu0=None, step0=0.01, max_bracket=20, tol=5e-3, max_bisect=30,
    verbose=True,
):
    """Verbatim from the notebooks."""
    rho = np.asarray(rho, float)
    N = np.asarray(N_counts, float)

    if rho_edges is None:
        lo, hi = float(np.min(rho)), float(np.max(rho))
        edges = np.linspace(lo, hi, int(rho_bins) + 1)
    else:
        edges = np.asarray(rho_edges, float)

    def f_of_mu(mu_trial):
        w = _weights_mu(N, mu_trial, mu_ref, beta=beta)
        ess = _ess(w)
        _, dens = _rho_hist_density(rho, w, edges)
        Ad = _area_in_window(edges, dens, *dilute_window)
        Ah = _area_in_window(edges, dens, *dense_window)
        return (Ah - Ad), ess, w, dens

    mu_start = float(mu_ref if mu0 is None else mu0)
    f0, ess0, w0, dens0 = f_of_mu(mu_start)
    if verbose:
        print(f"[equal-rho] mu0={mu_start:.6f}, dA={f0:+.4f}, ESS~{ess0:.0f}",
              flush=True)

    if abs(f0) < tol and ess0 >= ess_min:
        centers, _ = _rho_hist_density(rho, w0, edges)
        return dict(mu_star=mu_start, success=True, ess=float(ess0),
                    centers=centers, density_star=dens0, w_star=w0)

    direction = 1.0 if f0 > 0 else -1.0
    step = float(step0)

    for k in range(max_bracket):
        mu_try = mu_start + direction * step * (k + 1)
        ft, esst, wt, denst = f_of_mu(mu_try)
        if verbose:
            print(f"[equal-rho] bracket mu={mu_try:.6f}, dA={ft:+.4f}, "
                  f"ESS~{esst:.0f}", flush=True)
        if np.sign(ft) != np.sign(f0):
            if f0 > 0:
                mu_lo, f_lo, w_lo, dens_lo = mu_try, ft, wt, denst
                mu_hi, f_hi, w_hi, dens_hi = mu_start, f0, w0, dens0
            else:
                mu_lo, f_lo, w_lo, dens_lo = mu_start, f0, w0, dens0
                mu_hi, f_hi, w_hi, dens_hi = mu_try, ft, wt, denst
            break
    else:
        centers, _ = _rho_hist_density(rho, w0, edges)
        return dict(mu_star=mu_start, success=False, ess=float(ess0),
                    centers=centers, density_star=dens0, w_star=w0,
                    reason="failed to bracket")

    for it in range(max_bisect):
        mu_mid = 0.5 * (mu_lo + mu_hi)
        fm, essm, wm, densm = f_of_mu(mu_mid)
        if verbose:
            print(f"[equal-rho] bisect mu={mu_mid:.6f}, dA={fm:+.4f}, "
                  f"ESS~{essm:.0f}", flush=True)
        if abs(fm) < tol and essm >= ess_min:
            centers, _ = _rho_hist_density(rho, wm, edges)
            return dict(mu_star=mu_mid, success=True, ess=float(essm),
                        centers=centers, density_star=densm, w_star=wm)
        if np.sign(fm) == np.sign(f_lo):
            mu_lo, f_lo, w_lo, dens_lo = mu_mid, fm, wm, densm
        else:
            mu_hi, f_hi, w_hi, dens_hi = mu_mid, fm, wm, densm

    centers, _ = _rho_hist_density(rho, wm, edges)
    return dict(mu_star=mu_mid, success=False, ess=float(essm),
                centers=centers, density_star=densm, w_star=wm,
                reason="max bisection iterations")


def resample_at_mu_star(data: ReweightDataMU, mu_star: float, rng=None):
    """Verbatim from the notebooks (systematic / stratified resampling)."""
    if rng is None:
        rng = np.random.default_rng(1234)
    dG = -data.beta * (mu_star - data.mu0) * np.asarray(data.N_mu, float)
    dG -= dG.max()
    w = np.exp(dG)
    w /= max(w.sum(), 1e-300)
    c = np.cumsum(w)
    u0 = rng.random() / len(w)
    u = u0 + np.arange(len(w)) / len(w)
    idx = np.searchsorted(c, u, side="right")
    idx = np.clip(idx, 0, len(w) - 1)
    return dict(
        indices=idx,
        weights=w,
        rho_mu=data.rho_mu[idx].copy(),
        rho_total=data.rho_total[idx].copy(),
        N_mu=data.N_mu[idx].copy(),
        u=data.u[idx].copy(),
        C_ns=data.C_ns[idx].copy(),
        C_sp=data.C_sp[idx].copy(),
    )


# --- mixed-field fit (s, r) + KDE -------------------------------------------
def _wmean(x, w):
    return float(np.sum(w * x) / max(np.sum(w), 1e-300))


def _wstd(x, w):
    m = _wmean(x, w)
    v = _wmean((x - m) ** 2, w)
    return float(np.sqrt(max(v, 1e-300)))


def _kde_fixed_sigma_on_grid(x_samples, x_grid, sigma_x, w):
    x_samples = np.asarray(x_samples, float)
    x_grid = np.asarray(x_grid, float)
    w = np.asarray(w, float).ravel()
    w = np.where(np.isfinite(w) & (w > 0), w, 0.0)
    w /= max(w.sum(), 1e-300)

    u = (x_grid[:, None] - x_samples[None, :]) / sigma_x
    K = np.exp(-0.5 * u * u)
    P = (K @ w) / (sigma_x * np.sqrt(2 * np.pi))
    P /= max(_trapz(P, x_grid), 1e-300)
    return P


def fit_s_r_from_reweighted(rho, u, x_ref, P_ref, s_ref, *,
                            weights=None, L=None, beta_over_nu=1 / 8,
                            sigma_x=0.05, r_penalty=5e-2,
                            bounds_s=(-5.0, 5.0), bounds_r=(-1.0, 1.0),
                            w_asym=0.5):
    """Verbatim from the notebooks.

    Note `s_ref is not None` pins s inside the objective, so the returned
    fit['s'] is then whatever x0/bounds allow -- exactly the notebook's
    behaviour, kept so the two pipelines agree step for step.
    """
    rho = np.asarray(rho, float).ravel()
    u = np.asarray(u, float).ravel()
    x_ref = np.asarray(x_ref, float).ravel()
    P_ref = np.asarray(P_ref, float).ravel()

    if weights is None:
        w = np.ones_like(rho, float)
    else:
        w = np.asarray(weights, float).ravel()
        w = np.where(np.isfinite(w) & (w > 0), w, 0.0)
    w /= max(w.sum(), 1e-300)

    def build_x_pdf(s, r):
        M = rho - s * u
        M_center = _wmean(M, w)
        M_std = max(_wstd(M, w), 1e-300)
        x_samples = (M - M_center) / M_std
        P_est = _kde_fixed_sigma_on_grid(x_samples, x_ref, sigma_x, w)
        return 1.0 / M_std, x_samples, P_est

    def objective(theta):
        s, r = float(theta[0]), float(theta[1])
        if s_ref is not None:
            s = s_ref
        _, _, P_est = build_x_pdf(s, r)

        diff = P_est - P_ref
        match_L2 = _trapz(diff * diff, x_ref)

        P_mir = np.interp(-x_ref, x_ref, P_est)
        A = 0.5 * (P_est - P_mir)
        asym_L2 = _trapz(A * A, x_ref)

        return match_L2 + w_asym * asym_L2 + r_penalty * (r * r)

    x0 = np.array([0.0, 0.0], float)
    bounds = [bounds_s, bounds_r]

    res = minimize(objective, x0, method="L-BFGS-B", bounds=bounds,
                   options=dict(maxiter=300, ftol=1e-9))
    if (not res.success) or ("ABNORMAL" in str(res.message)):
        res = minimize(objective, res.x, method="Nelder-Mead",
                       options=dict(maxiter=800, xatol=1e-6, fatol=1e-6))

    s_opt, r_opt = map(float, res.x)
    alpha_opt, xs_opt, P_fit = build_x_pdf(s_opt, r_opt)

    diff = P_fit - P_ref
    match_L2 = float(_trapz(diff * diff, x_ref))
    P_mir = np.interp(-x_ref, x_ref, P_fit)
    A = 0.5 * (P_fit - P_mir)
    asym_L2 = float(_trapz(A * A, x_ref))

    return dict(success=bool(res.success), message=str(res.message),
                s=s_opt, r=r_opt, alpha=alpha_opt,
                x=x_ref, P_fit=P_fit, P_ref=P_ref,
                match_L2=match_L2, asym_L2=asym_L2, fun=float(res.fun))


# --- theta reweight objective (eps, mu) at fixed eps_d and fixed s -----------
def _parse_theta_with_s(theta):
    t = list(map(float, theta))
    be, beA, bm, L, Mc = t[:5]
    s = t[5] if len(t) >= 6 else 0.0
    return be, beA, bm, L, Mc, s


def kl_q_p(q, p, eps=1e-12):
    q = np.asarray(q, float)
    p = np.asarray(p, float)
    q = q / max(q.sum(), 1e-300)
    p = p / max(p.sum(), 1e-300)
    q = np.clip(q, eps, 1.0)
    p = np.clip(p, eps, 1.0)
    q /= q.sum()
    p /= p.sum()
    return float(np.sum(q * (np.log(q) - np.log(p))))


def js_div(q, p, eps=1e-12):
    q = np.asarray(q, float)
    p = np.asarray(p, float)
    q = q / max(q.sum(), 1e-300)
    p = p / max(p.sum(), 1e-300)
    q = np.clip(q, eps, 1.0)
    p = np.clip(p, eps, 1.0)
    q /= q.sum()
    p /= p.sum()
    m = 0.5 * (q + p)
    return 0.5 * kl_q_p(q, m, eps) + 0.5 * kl_q_p(p, m, eps)


def reweight_from_samples_counts_with_s(M_ref, C, Ca, N, theta_prime,
                                        theta_ref, *, rho=None, u=None,
                                        clip=700.0, return_Mprime=False):
    """Verbatim from the notebooks."""
    be, beA, bm, _, _, s_ref = _parse_theta_with_s(theta_ref)
    bep, beAp, bmp, _, _, s_prime = _parse_theta_with_s(theta_prime)

    if (rho is not None) and (u is not None):
        Mprime = np.asarray(rho, float) - float(s_prime) * np.asarray(u, float)
    else:
        Mprime = np.asarray(M_ref, float)

    d_be, d_beA, d_bm = (bep - be), (beAp - beA), (bmp - bm)
    logw = (-(d_be) * np.asarray(C, float)
            - (d_beA) * np.asarray(Ca, float)
            - (d_bm) * np.asarray(N, float))

    logw = np.clip(logw - np.max(logw), -clip, None)
    w = np.exp(logw)

    return (w, Mprime) if return_Mprime else w


def weighted_hist_and_sigma(x, w, edges, epsilon=1e-12, *,
                            return_nonempty=True, empty_tol=0.0):
    x = np.asarray(x, float)
    w = np.asarray(w, float)
    n = x.size
    K = len(edges) - 1

    idx = np.clip(np.digitize(x, edges) - 1, 0, K - 1)

    S1 = np.bincount(idx, weights=w, minlength=K)
    S2 = np.bincount(idx, weights=w * w, minlength=K)
    W = float(w.sum())

    p = S1 / max(W, epsilon)
    num = S2 - (S1 ** 2) / max(n, 1)
    sigma2 = np.maximum(num / max(W, epsilon), 0.0)
    centers = 0.5 * (edges[1:] + edges[:-1])

    if return_nonempty:
        nonempty = p > float(empty_tol)
        return centers, p, sigma2, nonempty
    return centers, p, sigma2


def make_objective_fixed_epsA_fixed_s_with_sweights(theta_ref, epsA_fixed,
                                                    rho, u, C, Ca, N,
                                                    edges_ref, p_ref, *,
                                                    L_fixed=None,
                                                    epsilon=1e-12):
    """Verbatim from the notebooks.  Returns JS(reweighted || Ising) at (eps, mu).

    Note the objective is evaluated on a *digitised* histogram, so it is
    piecewise constant in its arguments.  See the module docstring, point 9.
    """
    be_ref, beA_ref, bm_ref, L_ref, Mc_ref, s_ref = _parse_theta_with_s(theta_ref)
    if L_fixed is None:
        L_fixed = float(L_ref)

    widths = np.diff(edges_ref)
    q_mass = (p_ref * widths)
    q_mass /= max(q_mass.sum(), 1e-300)

    theta_ref_ext = (be_ref, beA_ref, bm_ref, L_ref, Mc_ref, s_ref, 0.0)

    def _wmean_std(x, w):
        W = max(w.sum(), 1e-300)
        m = float(np.dot(w, x) / W)
        v = float(np.dot(w, (x - m) ** 2) / W)
        return m, math.sqrt(max(v, 1e-300))

    def objective(x):
        be_p, bm_p = map(float, x[:2])
        theta_prime_ext = (be_p, float(epsA_fixed), bm_p, float(L_fixed),
                           0.0, s_ref, 0.0)

        w, Mprime = reweight_from_samples_counts_with_s(
            M_ref=rho - s_ref * u, C=C, Ca=Ca, N=N,
            theta_prime=theta_prime_ext, theta_ref=theta_ref_ext,
            rho=rho, u=u, return_Mprime=True)

        Mc_w, std_w = _wmean_std(Mprime, w)
        std_w = max(std_w, 1e-300)
        x_vals = (Mprime - Mc_w) / std_w

        _, p_mass, sigma2_mass, nonempty = weighted_hist_and_sigma(
            x_vals, w, edges_ref, return_nonempty=True)

        m = (p_mass > 0) | (q_mass > 0)
        return js_div(q_mass[m], p_mass[m])

    return objective


def optimize_eps_mu_Mc_fixed_epsA_fixed_s(theta_ref, epsA_fixed,
                                          rho, u, C, Ca, N, edges_ref, p_ref,
                                          *, L_fixed=None, x0=None,
                                          bounds=None, options=None,
                                          eps_halfwidth=0.02,
                                          mu_halfwidth=0.02):
    """Verbatim from the notebooks (L-BFGS-B on the JS objective).

    The only change is that the +-0.02 box around the reference is now named
    (eps_halfwidth / mu_halfwidth) instead of hard-coded, so the caller can
    widen it when the eps_d step is larger than the notebook's 0.02.
    """
    obj = make_objective_fixed_epsA_fixed_s_with_sweights(
        theta_ref, epsA_fixed, rho, u, C, Ca, N, edges_ref, p_ref,
        L_fixed=L_fixed)
    be_ref, beA_ref, bm_ref, L_ref, Mc_ref, s_ref = _parse_theta_with_s(theta_ref)
    if L_fixed is None:
        L_fixed = L_ref

    if x0 is None:
        x0 = np.array([be_ref, bm_ref], float)

    if bounds is None:
        bounds = [(be_ref - eps_halfwidth, be_ref + eps_halfwidth),
                  (bm_ref - mu_halfwidth, bm_ref + mu_halfwidth)]

    res = minimize(obj, x0=np.asarray(x0, float), method="L-BFGS-B",
                   bounds=bounds, options=options or dict(maxiter=400,
                                                          ftol=1e-5))
    be_p, bm_p = map(float, res.x)

    theta_ref_ext = (be_ref, beA_ref, bm_ref, L_ref, Mc_ref, s_ref, 0.0)
    theta_prime_ext = (be_p, float(epsA_fixed), bm_p, float(L_fixed), 0.0,
                       s_ref, 0.0)
    w, Mprime = reweight_from_samples_counts_with_s(
        M_ref=rho - s_ref * u, C=C, Ca=Ca, N=N,
        theta_prime=theta_prime_ext, theta_ref=theta_ref_ext,
        rho=rho, u=u, return_Mprime=True)
    W = max(w.sum(), 1e-300)
    Mc_w = float(np.dot(w, Mprime) / W)

    res.theta_star = (be_p, float(epsA_fixed), bm_p, float(L_fixed), Mc_w,
                      float(s_ref))
    res.objective = obj
    res.bounds = bounds
    return res


def s_admissible_range(rho, u, *, frac=0.5, s_bound=5.0):
    """The branch of s on which M = rho - s*u is a usable order parameter.

    rho and u are very strongly anticorrelated at coexistence -- measured
    corr = -0.997 at L=10 and -0.999 at L=20 for the bent system at
    eps_d = 1.8 -- because both count particle contacts.  So

        Var(M)(s) = Var(rho) - 2 s Cov(rho,u) + s^2 Var(u)

    has a minimum at s* = Cov(rho,u)/Var(u) where M very nearly vanishes:
    sigma(M)/sigma(rho) bottoms out at 0.075 (L=10) and 0.045 (L=20), at
    s* ~ -0.25 in both cases.

    That point is a singularity of the fit objective, and it matters because
    the objective standardises M and symmetrises the result.  On the far side
    of s*, M has flipped sign relative to rho, and a sign-flipped order
    parameter can score *better* than the physical one -- which is exactly
    what happens at L=10, where the objective's global minimum sits at
    s = -0.325, past the degeneracy, while the physical branch contains s = 0.

    Returns the connected interval containing s = 0 on which
    sigma(M) >= frac * sigma(rho).
    """
    rho = np.asarray(rho, float).ravel()
    u = np.asarray(u, float).ravel()
    vr = float(np.var(rho))
    vu = float(np.var(u))
    cov = float(np.mean((rho - rho.mean()) * (u - u.mean())))
    lo, hi = -float(s_bound), float(s_bound)
    if vu <= 0 or vr <= 0:
        return lo, hi, float("nan"), float("nan")

    s_sing = cov / vu
    sig_min = math.sqrt(max(vr - cov * cov / vu, 0.0)) / math.sqrt(vr)

    # solve Var(M)(s) = frac^2 Var(rho)
    a, b, c = vu, -2.0 * cov, vr * (1.0 - frac * frac)
    disc = b * b - 4 * a * c
    if disc > 0:
        r1 = (-b - math.sqrt(disc)) / (2 * a)
        r2 = (-b + math.sqrt(disc)) / (2 * a)
        blo, bhi = min(r1, r2), max(r1, r2)
        if blo < 0.0 < bhi:
            # 0 itself is inside the degenerate band: nothing is admissible.
            return float("nan"), float("nan"), s_sing, sig_min
        if bhi <= 0.0:
            lo = bhi
        else:
            hi = blo
    return lo, hi, s_sing, sig_min


def profile_s(rho, u, x_ref, P_ref, *, s_grid=None, sigma_x=0.03,
              r_penalty=1e-1, w_asym=2.0, weights=None):
    """Profile the mixed-field fit objective over s.

    Worth knowing before reading the result: in the notebook's
    `fit_s_r_from_reweighted`, r does NOT enter `build_x_pdf` at all -- it
    appears only through the `r_penalty * r**2` term.  So the optimum is always
    r = 0, Lambda = 1 - s*r is always 1 (which is what the logged theta* records
    show), and the objective is a function of s ALONE.  This one-dimensional
    profile is therefore the complete picture of that fit, not a slice through
    it.

    Returns the objective and its two parts, plus P(x) at each s, so a caller
    can see whether a fitted s sits in a real minimum or on a plateau.
    """
    rho = np.asarray(rho, float).ravel()
    u = np.asarray(u, float).ravel()
    x_ref = np.asarray(x_ref, float).ravel()
    P_ref = np.asarray(P_ref, float).ravel()
    if s_grid is None:
        s_grid = np.linspace(-1.0, 1.0, 161)
    s_grid = np.asarray(s_grid, float)

    if weights is None:
        w = np.ones_like(rho, float)
    else:
        w = np.asarray(weights, float).ravel()
        w = np.where(np.isfinite(w) & (w > 0), w, 0.0)
    w /= max(w.sum(), 1e-300)

    obj = np.empty(s_grid.size)
    match = np.empty(s_grid.size)
    asym = np.empty(s_grid.size)
    P_all = np.empty((s_grid.size, x_ref.size))

    for i, s in enumerate(s_grid):
        M = rho - float(s) * u
        m = _wmean(M, w)
        sd = max(_wstd(M, w), 1e-300)
        P_est = _kde_fixed_sigma_on_grid((M - m) / sd, x_ref, sigma_x, w)
        d = P_est - P_ref
        match[i] = float(_trapz(d * d, x_ref))
        P_mir = np.interp(-x_ref, x_ref, P_est)
        A = 0.5 * (P_est - P_mir)
        asym[i] = float(_trapz(A * A, x_ref))
        obj[i] = match[i] + w_asym * asym[i]
        P_all[i] = P_est

    return dict(s_grid=s_grid, obj=obj, match=match, asym=asym, P=P_all,
                x=x_ref, P_ref=P_ref)


def equal_area_mu_reweight(rho, C, Ca, N, u, theta_ref, eps_new, epsA_fixed,
                           s_ref, L_fixed, dilute_window, dense_window,
                           mu_lo, mu_hi, tol=1e-4, max_iter=60):
    """mu that balances the two basins at eps_new, by reweighting alone.

    The scan must not be free to choose mu.  The standardised variable has zero
    mean by construction, so p_L*|c_L| = p_R*|c_R| identically: if the basins
    carry unequal weight, the lighter peak is pushed outward, the distribution
    looks asymmetric, and JS reports a mismatch that is arithmetic rather than
    physics.  Measured at eps_d = 1.8: 0.503/0.497 at L=10 against 0.525/0.475
    at L=20, which was the entire dense-peak displacement.

    Costs nothing -- it is a bisection over the same importance weights the
    objective already forms.
    """
    be_ref, beA_ref, bm_ref, _, Mc_ref, _ = _parse_theta_with_s(theta_ref)
    theta_ref_ext = (be_ref, beA_ref, bm_ref, L_fixed, Mc_ref, s_ref, 0.0)
    rho = np.asarray(rho, float)
    dil = (rho >= dilute_window[0]) & (rho < dilute_window[1])
    den = (rho >= dense_window[0]) & (rho <= dense_window[1])

    def imbalance(mu):
        w = reweight_from_samples_counts_with_s(
            M_ref=None, C=C, Ca=Ca, N=N,
            theta_prime=(eps_new, float(epsA_fixed), mu, float(L_fixed), 0.0,
                         s_ref, 0.0),
            theta_ref=theta_ref_ext, rho=rho, u=u)
        W = max(w.sum(), 1e-300)
        return float(w[den].sum() / W - w[dil].sum() / W)

    lo, hi = float(mu_lo), float(mu_hi)
    f_lo, f_hi = imbalance(lo), imbalance(hi)
    # mu enters as an occupancy penalty, so imbalance decreases with mu; widen
    # the bracket if the requested window does not contain the root.
    for _ in range(8):
        if f_lo * f_hi <= 0:
            break
        span = hi - lo
        lo -= span
        hi += span
        f_lo, f_hi = imbalance(lo), imbalance(hi)
    if f_lo * f_hi > 0:
        return float(bm_ref), False
    for _ in range(max_iter):
        mid = 0.5 * (lo + hi)
        f = imbalance(mid)
        if abs(f) < tol:
            return float(mid), True
        if f * f_lo > 0:
            lo, f_lo = mid, f
        else:
            hi, f_hi = mid, f
    return float(0.5 * (lo + hi)), True


def scan_eps_mu_fixed_epsA_fixed_s(theta_ref, epsA_fixed,
                                   rho, u, C, Ca, N, edges_ref, p_ref, *,
                                   L_fixed=None, eps_halfwidth=0.02,
                                   mu_halfwidth=0.02, n_eps=81, n_mu=41,
                                   smooth_pts=7, fit_pts=9, ess_floor=0.0,
                                   mu_mode="equal-area",
                                   dilute_window=(0.0, 0.4),
                                   dense_window=(0.6, 1.0),
                                   verbose=False):
    """Grid scan of the SAME objective, used only to rescue stalled steps.

    L-BFGS-B on a piecewise-constant objective can terminate at its starting
    point (mc_fss FINDINGS 4.1).  In continuation mode that shows up as a step
    where eps_nd does not move at all -- which is what produced the runs of
    3-4 frozen entries in the logged bent-geometry trace.  When --scan-fallback
    is on, such a step is redone here: profile JS over eps at the best mu, then
    fit a local parabola to the minimum.
    """
    be_ref, beA_ref, bm_ref, L_ref, Mc_ref, s_ref = _parse_theta_with_s(theta_ref)
    if L_fixed is None:
        L_fixed = L_ref
    obj = make_objective_fixed_epsA_fixed_s_with_sweights(
        theta_ref, epsA_fixed, rho, u, C, Ca, N, edges_ref, p_ref,
        L_fixed=L_fixed)

    eps_grid = np.linspace(be_ref - eps_halfwidth, be_ref + eps_halfwidth,
                           int(n_eps))
    mu_grid = np.linspace(bm_ref - mu_halfwidth, bm_ref + mu_halfwidth,
                          int(n_mu))

    prof = np.empty(eps_grid.size)
    mu_at = np.empty(eps_grid.size)
    n_ea_fail = 0
    for i, e in enumerate(eps_grid):
        if mu_mode == "equal-area":
            m_ea, ok_ea = equal_area_mu_reweight(
                rho, C, Ca, N, u, theta_ref, e, epsA_fixed, s_ref, L_fixed,
                dilute_window, dense_window, mu_grid[0], mu_grid[-1])
            n_ea_fail += int(not ok_ea)
            mu_at[i] = m_ea
            prof[i] = obj([e, m_ea])
        else:
            vals = np.array([obj([e, m]) for m in mu_grid])
            j = int(np.argmin(vals))
            prof[i] = vals[j]
            mu_at[i] = mu_grid[j]
    if verbose and mu_mode == "equal-area" and n_ea_fail:
        print(f"[scan] equal-area mu could not be bracketed at "
              f"{n_ea_fail}/{eps_grid.size} grid points", flush=True)

    # ESS along the profile, computed BEFORE the minimum is chosen.  This is
    # what makes a wide window safe: scan far enough to contain the
    # displacement, then refuse to pick a minimum from the part of the window
    # where the reweighting is carried by a handful of configurations.
    theta_ref_ext = (be_ref, beA_ref, bm_ref, L_ref, Mc_ref, s_ref, 0.0)
    n = np.asarray(rho, float).size
    ess = np.empty(eps_grid.size)
    for i, (e, m) in enumerate(zip(eps_grid, mu_at)):
        w = reweight_from_samples_counts_with_s(
            M_ref=None, C=C, Ca=Ca, N=N,
            theta_prime=(e, float(epsA_fixed), m, float(L_fixed), 0.0,
                         s_ref, 0.0),
            theta_ref=theta_ref_ext, rho=rho, u=u)
        ess[i] = _ess(w) / max(n, 1)

    ok = ess >= float(ess_floor)
    if not ok.any():
        ok = np.ones_like(ess, dtype=bool)
    frac_ok = float(np.mean(ok))

    # light smoothing, then a local quadratic around the discrete minimum
    k = max(1, int(smooth_pts) | 1)
    if k > 1 and prof.size > k:
        ker = np.ones(k) / k
        sm = np.convolve(np.pad(prof, (k // 2, k // 2), mode="edge"), ker,
                         mode="valid")
    else:
        sm = prof
    i0 = int(np.argmin(np.where(ok, sm, np.inf)))

    # Is the chosen point at an edge of the ADMISSIBLE region?  That is the
    # honest "no interior minimum" test -- the raw window edge is not, once
    # part of the window has been masked away.
    idx_ok = np.flatnonzero(ok)
    at_edge = bool(i0 <= idx_ok[0] or i0 >= idx_ok[-1])

    lo = max(int(idx_ok[0]), i0 - int(fit_pts) // 2)
    hi = min(int(idx_ok[-1]) + 1, i0 + int(fit_pts) // 2 + 1)
    eps_star = float(eps_grid[i0])
    curvature = float("nan")
    if hi - lo >= 3 and not at_edge:
        c = np.polyfit(eps_grid[lo:hi], sm[lo:hi], 2)
        if c[0] > 0:
            cand = -0.5 * c[1] / c[0]
            if eps_grid[lo] <= cand <= eps_grid[hi - 1]:
                eps_star = float(cand)
                curvature = float(2.0 * c[0])
    mu_star = float(np.interp(eps_star, eps_grid, mu_at))
    js_star = float(obj([eps_star, mu_star]))

    if verbose:
        print(f"[scan] eps*={eps_star:.6f} mu*={mu_star:.6f} JS={js_star:.5f} "
              f"curv={curvature:.3g}  ESS/n at min "
              f"{np.interp(eps_star, eps_grid, ess):.2f}  "
              f"window admissible {100 * frac_ok:.0f}% "
              f"(ESS/n >= {ess_floor:g})"
              f"{'  AT ADMISSIBLE EDGE' if at_edge else ''}", flush=True)

    return dict(eps_nd=eps_star, mu=mu_star, js=js_star,
                curvature=curvature, eps_grid=eps_grid, prof=prof,
                mu_at=mu_at, ess=ess, admissible=ok, frac_admissible=frac_ok,
                at_edge=at_edge)


# --- mu search by simulation ------------------------------------------------
def find_mu_equal_areas_by_simulation(simulate, mu0,
                                      dilute_window=(0.00, 0.30),
                                      dense_window=(0.70, 1.00),
                                      step0=0.02, tol=2e-2, max_iters=50,
                                      verbose=True):
    """Verbatim from the notebooks, plus a geometric pre-bracket.

    The notebook's fixed-step search creeps at `step0` per iteration and cannot
    recover an O(1) error in mu inside its iteration cap.  Within a
    continuation that is fine -- mu moves by ~d(eps_d) per step -- but the very
    first step of a segment starts from an anchor measured at a different L,
    where the offset can be much larger.  The pre-bracket doubles the step
    until the sign of (m_dense - m_dilute) flips, then hands the bracket to the
    original bisection.
    """
    def basin_masses(rho):
        rho = np.asarray(rho, float)
        m_dil = ((rho >= dilute_window[0]) & (rho < dilute_window[1])).mean()
        m_den = ((rho >= dense_window[0]) & (rho <= dense_window[1])).mean()
        return float(m_dil), float(m_den)

    cache = {}

    def mass_diff_at(mu):
        mu = float(mu)
        mu_key = float(np.round(mu, 12))
        if mu_key in cache:
            return cache[mu_key]
        data = simulate(mu)
        m_dil, m_den = basin_masses(data.rho_mu)
        f = float(m_den - m_dil)
        cache[mu_key] = (f, data)
        return cache[mu_key]

    mu = float(mu0)
    f, data = mass_diff_at(mu)
    if verbose:
        print(f"[mu={mu:.6f}] f=m_dense-m_dilute={f:+.4f}", flush=True)

    best = (abs(f), mu, data)
    bracket = None

    # --- geometric pre-bracket ------------------------------------------
    if abs(f) > tol:
        step = float(step0)
        for _ in range(12):
            mu_try = mu + (step if f > 0 else -step)
            f_try, d_try = mass_diff_at(mu_try)
            if verbose:
                print(f"[pre-bracket] mu={mu_try:.6f} f={f_try:+.4f} "
                      f"step={step:.4f}", flush=True)
            if abs(f_try) < best[0]:
                best = (abs(f_try), mu_try, d_try)
            if abs(f_try) <= tol:
                return {"mu": mu_try, "success": True, "data": d_try,
                        "iters": 0, "n_sim": len(cache)}
            if f * f_try < 0.0:
                bracket = ((mu, f, mu_try, f_try) if f < 0
                           else (mu_try, f_try, mu, f))
                break
            step *= 2.0
        # If no flip was found the loop falls through to the original walk.

    for it in range(1, int(max_iters) + 1):
        if abs(f) <= tol:
            return {"mu": mu, "success": True, "data": data, "iters": it - 1,
                    "n_sim": len(cache)}

        if bracket is not None:
            mu_lo, f_lo, mu_hi, f_hi = bracket
            mu = 0.5 * (mu_lo + mu_hi)
            f, data = mass_diff_at(mu)
            if verbose:
                print(f"[bisect] mu={mu:.6f} f={f:+.4f} "
                      f"bracket=[{mu_lo:.6f},{mu_hi:.6f}]", flush=True)
            if abs(f) < best[0]:
                best = (abs(f), mu, data)
            if f < 0:
                bracket = (mu, f, mu_hi, f_hi)
            else:
                bracket = (mu_lo, f_lo, mu, f)
            continue

        mu_new = mu + (step0 if f > 0 else -step0)
        f_new, data_new = mass_diff_at(mu_new)
        if verbose:
            print(f"[step] mu={mu_new:.6f} f={f_new:+.4f}", flush=True)

        if abs(f_new) < best[0]:
            best = (abs(f_new), mu_new, data_new)

        if f != 0.0 and f_new != 0.0 and (f * f_new < 0.0):
            bracket = ((mu, f, mu_new, f_new) if f < 0
                       else (mu_new, f_new, mu, f))

        mu, f, data = mu_new, f_new, data_new

    _, mu_best, data_best = best
    return {"mu": mu_best, "success": False, "data": data_best,
            "iters": int(max_iters), "n_sim": len(cache)}


# ----------------------------------------------------------------------------
# lattice construction
# ----------------------------------------------------------------------------
def make_lattices(species, L, mode, rng):
    """Initial configurations.

    'middle' reproduces the notebook exactly: every replica starts from the
    same random mixture with weights [1,...,1,4] over (orientations, vacancy).
    'mixed' additionally supplies a dilute and a dense start, so that agreement
    between replicas started from opposite basins is itself an equilibration
    test -- which matters at L=30, where a single chain may not tunnel.
    """
    n = len(species)
    N_total = L * L
    ids = np.arange(n, dtype=np.int64)

    def from_weights(wts):
        wts = np.asarray(wts, float)
        wts = wts / wts.sum()
        counts = [int(w * N_total) for w in wts]
        counts[0] += N_total - sum(counts)
        flat = np.concatenate([np.full(c, ids[i], dtype=np.int64)
                               for i, c in enumerate(counts)])
        rng.shuffle(flat)
        return flat.reshape((L, L))

    w_middle = np.array(list(np.ones(n - 1)) + [4.0])
    lat_middle = from_weights(w_middle)
    if mode == "middle":
        return [lat_middle]

    w_dilute = np.array(list(np.ones(n - 1) * 0.1) + [float(n - 1) * 0.9 / 0.1])
    w_dense = np.array(list(np.ones(n - 1)) + [0.15 * (n - 1)])
    lat_dilute = from_weights(w_dilute)
    lat_dense = from_weights(w_dense)
    return [lat_dense, lat_dilute, lat_middle]


# ----------------------------------------------------------------------------
# configuration
# ----------------------------------------------------------------------------
@dataclass
class SweepConfig:
    # --- what to run ------------------------------------------------------
    system: str = "l"
    L: int = 10
    seed: int = 0

    # segment of the critical line: eps_d from eps_sp_start to eps_sp_end,
    # inclusive of the end, in steps of eps_sp_step.
    eps_sp_start: float = 0.0
    eps_sp_end: float = 0.4
    eps_sp_step: float = 0.02

    # anchor at eps_sp_start.  For a segment starting at eps_d=0 leave these
    # None and the exact lattice-gas values are used.
    eps_ns0: Optional[float] = None
    mu0: Optional[float] = None
    s0: Optional[float] = None        # field mixing; None -> refit each step

    # --- statistics -------------------------------------------------------
    # steps(L) = sweeps_ref * (L/L_ref)^z * L^2
    sweeps_ref: float = 6.0e6
    L_ref: int = 10
    z_exponent: float = 2.17
    n_replicas: int = 8
    n_workers: int = 0                # 0 -> n_replicas
    samples_per_replica: int = 6000
    burn_frac: float = 0.10
    scout_frac: float = 0.08          # 1.0 reproduces the notebook exactly
    scout_burn_frac: float = 0.40
    max_blocks: int = 10_000

    # --- estimator knobs (notebook values) --------------------------------
    dilute_window: Tuple[float, float] = (0.00, 0.40)
    dense_window: Tuple[float, float] = (0.60, 1.00)
    scout_step0: float = 0.004
    scout_tol: float = 1e-1
    ess_frac: float = 0.40
    sigma_x: float = 0.03
    r_penalty: float = 1e-1
    w_asym: float = 2.0
    mu_reweight_step0: float = 1e-4
    mu_reweight_tol: float = 1e-2
    rho_bins: int = 200

    # box for the (eps_nd, mu) reweighting optimiser.  The notebook hard-codes
    # +-0.02, which is matched to its eps_d step of 0.02.  Scale with the step
    # so a coarser sweep is not silently clipped at the bound.
    opt_halfwidth_per_step: float = 1.0

    # --- relocation at fixed eps_d ---------------------------------------
    # The notebook's loop opens with eps_sp == eps_sp_prev, i.e. a pass with
    # ZERO displacement in eps_d that just re-asks "is this still the critical
    # point?".  At larger L that is the single most informative thing you can
    # run: it says whether the logged L=10 anchor is a critical point at this
    # L at all, and whether the chains tunnel there, before any sweep time is
    # spent.  It is also the one case where L-BFGS-B is useless -- with
    # d(eps_d)=0 there is no displacement to put it on the steep flank, and it
    # terminates at its starting point (mc_fss FINDINGS 4.1) -- so this pass
    # always uses the grid scan regardless of scan_fallback.
    relocate_first: bool = False
    # Scan half-width in eps_nd.  This used to be 0.08 scaled as L_ref/L, on
    # the argument that the ESS-usable range narrows with L (the log-weights
    # carry C ~ L^2).  That was the wrong knob: the window shrank as 1/L while
    # the displacement it has to contain does not.  Measured at eps_d = 1.8,
    # bent: eps_nd,c(20) sits at or below 1.3131, i.e. >= 0.040 below the L=10
    # anchor -- already outside the +-0.0267 window that L_ref/L scaling gave
    # L=30, which is why L=30 returned JS = 0.145 and no minimum.  So: scan
    # WIDE, and let the ESS floor below decide which part of the window is
    # usable, rather than guessing the range in advance.
    relocate_halfwidth: float = 0.15
    relocate_scale_with_L: bool = False
    relocate_mu_halfwidth: float = 0.05
    # A grid point is only eligible to be the minimum if ESS/n is at least
    # this.  Without it a wide window can pick its minimum out of the noise in
    # the ESS-dead tail.
    relocate_ess_floor: float = 0.15
    # "equal-area" pins mu to the balanced-basin value at each eps_nd.
    # "free" restores the old behaviour of letting JS pick mu, which put the
    # located point off coexistence and manufactured an apparent asymmetry.
    scan_mu_mode: str = "equal-area"
    relocate_n_eps: int = 121
    relocate_n_mu: int = 51
    # Store the JS(eps_nd) profile, the s profile, and the resampled (rho, u)
    # for every relocation pass.  Costs seconds and a few hundred kB, and is
    # the only way to tell "the minimum is outside the window" from "there is
    # no minimum" after the fact.
    store_diagnostics: bool = True
    s_profile_lo: float = -1.0
    s_profile_hi: float = 1.0
    s_profile_n: int = 161

    # --- the mixed-field fit ----------------------------------------------
    # "lbfgs" is the notebook's call verbatim.  It optimises a KDE-of-a-comb
    # objective with a default finite-difference step of 1e-8, and at small L
    # -- where rho has only L^2+1 attainable levels, so x is a comb rather
    # than a continuum -- that gradient is noise and the optimiser can walk
    # uphill to its own bound.  Observed directly at L=10: it returned
    # s = +5.00000 (the bound) at objective 0.846, while the grid minimum of
    # the SAME objective sits at s = -0.325, objective 0.207.  At L=20 the
    # fit and the grid agree to four decimals.
    # "auto" keeps the notebook's optimiser and only intervenes when it lands
    # on a bound, which costs nothing in the healthy case.
    s_estimator: str = "auto"          # lbfgs | auto | grid
    s_bound: float = 5.0
    s_guard_n: int = 81
    # sigma(M) must stay at least this fraction of sigma(rho): cuts the search
    # at the rho/u collinearity singularity.
    s_degeneracy_frac: float = 0.5
    # if the objective varies by less than this *relative* amount over the
    # admissible branch, s is not identifiable from the data and the fitted
    # value is noise.
    s_identifiable_span: float = 0.05
    # used when the fit objective has no interior minimum on the physical
    # branch.  0.0 means "pure density order parameter, M = rho", which is
    # what the logged trace values (|s| ~ 0.01) are indistinguishable from.
    s_fallback: float = 0.0

    # --- robustness -------------------------------------------------------
    scan_fallback: bool = False
    stall_tol: float = 1e-9
    max_abs_eps_step: float = 0.10    # reject an implausible jump in eps_nd
    min_crossings_warn: int = 1

    # --- bookkeeping ------------------------------------------------------
    init_mode: str = "middle"
    beta: float = 1.0
    ising_cache: Optional[str] = None
    checkpoint: Optional[str] = None
    archive_raw: bool = False
    verbose_inner: bool = False

    def steps_for(self, L=None):
        L = self.L if L is None else L
        sweeps = self.sweeps_ref * (float(L) / float(self.L_ref)) ** self.z_exponent
        return int(round(sweeps * L * L))

    def eps_sp_grid(self):
        """Targets for the continuation loop.

        With relocate_first, the first target equals eps_sp_start -- a
        zero-displacement pass -- which is exactly the notebook's first loop
        iteration.  Without it the grid starts one step in, since that pass
        costs a full chain and moves nothing when the anchor is already good.
        """
        n = int(round((self.eps_sp_end - self.eps_sp_start) / self.eps_sp_step))
        n = max(n, 0)
        g = self.eps_sp_start + self.eps_sp_step * np.arange(1, n + 1)
        if self.relocate_first:
            g = np.concatenate([[self.eps_sp_start], g])
        return g


# ----------------------------------------------------------------------------
# the driver: one segment of the critical line
# ----------------------------------------------------------------------------
def _ckpt_fingerprint(cfg: SweepConfig):
    """Everything about cfg that changes the NUMBERS.

    A checkpoint carrying a different fingerprint is not a resumable state, it
    is a different calculation.  Resuming across one silently returns the old
    answer -- which is exactly what happens after FORCE=1 overwrites the .npz
    but leaves ck_*.json in place: the grid is already exhausted, the loop body
    never runs, and the stale points are written straight back out.
    """
    keys = ("system", "L", "seed", "eps_sp_start", "eps_sp_end",
            "eps_sp_step", "eps_ns0", "mu0", "s0", "sweeps_ref", "L_ref",
            "z_exponent", "n_replicas", "samples_per_replica", "burn_frac",
            "scout_frac", "scout_burn_frac", "relocate_first",
            "relocate_halfwidth", "relocate_scale_with_L",
            "relocate_ess_floor", "scan_mu_mode", "s_estimator", "init_mode",
            "beta")
    return {k: getattr(cfg, k) for k in keys}


def run_segment(cfg: SweepConfig, verbose=True):
    """Walk eps_d from cfg.eps_sp_start to cfg.eps_sp_end at fixed L.

    One iteration reproduces one pass of the notebook's `for eps_sp in eps_sps`
    loop:

      1. equal-area mu at the CURRENT (eps_ns, eps_sp_prev)     [short chains]
      2. production chain at that mu                            [full length]
      3. mu* by reweighting in mu
      4. resample at mu*, fit the mixed field (s, r)
      5. reweight (eps_ns, mu) from eps_sp_prev to eps_sp, minimising JS
      6. record, advance eps_sp_prev
    """
    import multiprocessing as mp

    sysdef = SYSTEMS[cfg.system]
    species = get_species_list_ind(sysdef["species"])
    n_species = len(species)
    empty_index = n_species - 1
    species_mu_indices = np.arange(n_species - 1, dtype=np.int64)

    eps_ns0, mu0 = lattice_gas_anchor(cfg.system)
    eps_ns = float(cfg.eps_ns0) if cfg.eps_ns0 is not None else eps_ns0
    mu = float(cfg.mu0) if cfg.mu0 is not None else mu0
    eps_sp_prev = float(cfg.eps_sp_start)
    s_ref = cfg.s0

    grid = cfg.eps_sp_grid()
    points: List[Dict] = []
    start_index = 0

    # --- resume from checkpoint ------------------------------------------
    if cfg.checkpoint and os.path.exists(cfg.checkpoint):
        with open(cfg.checkpoint) as fh:
            st = json.load(fh)

        fp_now = _ckpt_fingerprint(cfg)
        fp_old = st.get("fingerprint")
        ver_old = st.get("code_version", 0)
        if ver_old != MC_LINE_VERSION or fp_old != fp_now:
            diffs = []
            if ver_old != MC_LINE_VERSION:
                diffs.append(f"code_version {ver_old} -> {MC_LINE_VERSION}")
            for k, v in fp_now.items():
                if fp_old is None or fp_old.get(k) != v:
                    old = "<absent>" if fp_old is None else fp_old.get(k)
                    diffs.append(f"{k}: {old!r} -> {v!r}")
            raise SystemExit(
                "\nREFUSING TO RESUME: the checkpoint\n"
                f"    {cfg.checkpoint}\n"
                "was written by a different calculation, so resuming it would "
                "return the older\nanswer rather than recomputing.  What "
                "changed:\n"
                + "".join(f"    {d}\n" for d in diffs[:12])
                + "\nDelete the checkpoint to start this one fresh:\n"
                f"    rm -f {cfg.checkpoint}\n")

        points = st.get("points", [])
        eps_ns = float(st["eps_ns"])
        mu = float(st["mu"])
        eps_sp_prev = float(st["eps_sp_prev"])
        s_ref = st.get("s_ref", s_ref)
        start_index = int(st.get("next_index", len(points)))
        if verbose:
            print(f"[resume] {cfg.checkpoint}: {len(points)} steps done, "
                  f"eps_d_prev={eps_sp_prev:.4f} eps_nd={eps_ns:.6f} "
                  f"mu={mu:.6f}", flush=True)

    if verbose:
        print(f"[setup] system={cfg.system} L={cfg.L} seed={cfg.seed}",
              flush=True)
        print(f"[setup] n_species={n_species} "
              f"patches={[list(map(int, p.patches)) for p in species]}",
              flush=True)
        print(f"[setup] segment eps_d {cfg.eps_sp_start:.4f} -> "
              f"{cfg.eps_sp_end:.4f} step {cfg.eps_sp_step:.4f} "
              f"({grid.size} steps)", flush=True)
        print(f"[setup] anchor eps_nd={eps_ns:.6f} mu={mu:.6f} "
              f"s={'refit' if s_ref is None else f'{s_ref:.5f}'}", flush=True)

    centers_ref, edges_ref, P_smooth = ising_reference(
        cache_path=cfg.ising_cache, verbose=verbose)
    P_ref = P_smooth / _trapz(P_smooth, centers_ref)

    rng = np.random.default_rng(cfg.seed * 7919 + 17)
    rng_shuffle = np.random.default_rng(cfg.seed * 104729 + 3)
    rng_resample = np.random.default_rng(cfg.seed * 6151 + 11)
    lattices = make_lattices(species, cfg.L, cfg.init_mode, rng)

    steps_prod = cfg.steps_for()
    steps_scout = max(int(steps_prod * cfg.scout_frac), 10_000)

    def _plan(steps):
        return dict(steps=int(steps),
                    snap=max(int(steps) // cfg.samples_per_replica, 1),
                    block=max(1000, int(steps) // cfg.max_blocks))

    P_prod, P_scout = _plan(steps_prod), _plan(steps_scout)
    buf = cfg.samples_per_replica + 16
    n_total = cfg.n_replicas * int(cfg.samples_per_replica * (1 - cfg.burn_frac))
    ess_min = cfg.ess_frac * n_total

    if verbose:
        print(f"[setup] steps/replica  production={steps_prod:.3e} "
              f"({steps_prod / cfg.L ** 2:.3e} sweeps)  "
              f"scout={steps_scout:.3e}", flush=True)
        print(f"[setup] replicas={cfg.n_replicas} "
              f"samples/replica={cfg.samples_per_replica} "
              f"n_total~{n_total} ess_min={ess_min:.0f}", flush=True)
        print(f"[setup] snapshot_interval={P_prod['snap']} "
              f"block_size={P_prod['block']} buffer={buf}", flush=True)

    payload = dict(species=species, species_mu_indices=species_mu_indices,
                   empty_index=empty_index, beta=cfg.beta)
    nw = cfg.n_workers or cfg.n_replicas
    ctx = mp.get_context("fork")
    pool = ctx.Pool(processes=int(nw), initializer=_worker_init,
                    initargs=(payload, cfg.seed + 1))
    if verbose:
        print(f"[setup] worker pool: {nw} processes (fork, numba reseeded)",
              flush=True)

    call_counter = [0]

    def _sim(eps_ns_cur, eps_sp_cur, mu_trial, plan, burn, keep_raw=False):
        call_counter[0] += 1
        return build_data_mu(
            pool, lattices, species, species_mu_indices,
            eps_ns_cur, eps_sp_cur, mu_trial, cfg.beta,
            plan["steps"], plan["snap"], buf, plan["block"],
            cfg.n_replicas, burn, rng_shuffle, cfg.L,
            call_id=call_counter[0], keep_raw=keep_raw)

    last_raw = {}
    diag_arrays = {}
    try:
        for i in range(start_index, grid.size):
            eps_sp = float(grid[i])
            t_step = time.perf_counter()
            if verbose:
                print(f"\n=== Step {i + 1}/{grid.size}: target eps_d={eps_sp:.4f} "
                      f"(prev={eps_sp_prev:.4f})  L={cfg.L} ===", flush=True)

            # --- 1. equal-area mu, short chains --------------------------
            def simulate(mu_trial):
                return _sim(eps_ns, eps_sp_prev, mu_trial, P_scout,
                            cfg.scout_burn_frac)

            guard = find_mu_equal_areas_by_simulation(
                simulate, mu0=mu,
                dilute_window=cfg.dilute_window,
                dense_window=cfg.dense_window,
                step0=cfg.scout_step0, tol=cfg.scout_tol,
                verbose=cfg.verbose_inner or verbose)
            mu = float(guard["mu"])

            # --- 2. production chain at that mu --------------------------
            data_mu = _sim(eps_ns, eps_sp_prev, mu, P_prod, cfg.burn_frac,
                           keep_raw=cfg.archive_raw)
            diag = data_mu.diag

            rho = data_mu.rho_mu
            u = data_mu.u
            C = data_mu.C_ns
            Ca = data_mu.C_sp
            N = data_mu.N_mu

            # --- 3. mu* by reweighting in mu -----------------------------
            res_equal = equal_peak_mu_in_rho_by_reweighting(
                rho, N, mu, beta=cfg.beta,
                rho_edges=np.linspace(0.0, 1.0, cfg.rho_bins + 1),
                dilute_window=cfg.dilute_window,
                dense_window=cfg.dense_window,
                ess_min=ess_min, step0=cfg.mu_reweight_step0,
                tol=cfg.mu_reweight_tol,
                verbose=cfg.verbose_inner)
            mu_star = float(res_equal["mu_star"])
            ess_mu = float(res_equal["ess"])

            # --- 4. resample at mu*, fit the mixed field -----------------
            rw = resample_at_mu_star(data_mu, mu_star, rng=rng_resample)
            rho_r = rw["rho_mu"]
            u_r = rw["u"]
            C_r = rw["C_ns"]
            Ca_r = rw["C_sp"]
            N_r = rw["N_mu"]

            # Confine the fit to the branch of s on which M = rho - s*u is a
            # usable order parameter (see s_admissible_range).
            s_lo, s_hi, s_sing, s_sigmin = s_admissible_range(
                rho_r, u_r, frac=cfg.s_degeneracy_frac, s_bound=cfg.s_bound)
            if not np.isfinite(s_lo):
                s_lo, s_hi = -cfg.s_bound, cfg.s_bound
                print("[warn] s = 0 lies inside the rho/u degeneracy band; "
                      "the mixed-field fit is not identifiable here. "
                      "Use --s0 with the logged trace value.", flush=True)
            if cfg.s_estimator == "lbfgs":
                s_lo, s_hi = -cfg.s_bound, cfg.s_bound

            fit = fit_s_r_from_reweighted(
                rho=rho_r, u=u_r, x_ref=centers_ref, s_ref=s_ref,
                P_ref=P_ref, weights=None, L=cfg.L,
                sigma_x=cfg.sigma_x, r_penalty=cfg.r_penalty,
                w_asym=cfg.w_asym, bounds_s=(s_lo, s_hi))
            s_fit = float(fit["s"])
            r_fit = float(fit["r"])

            # Guard the mixed-field fit.  See SweepConfig.s_estimator.
            #
            # The objective is one-dimensional (r is inert), bounded, and
            # evaluated on a KDE of a comb, so a grid + local parabola is both
            # cheaper and far more robust than a quasi-Newton method with a
            # 1e-8 finite-difference step.  Measured at production sample
            # counts: an 81-point profile costs ~10 s against a 3 min (L=10)
            # to 5 h (L=30) MC step, i.e. nothing.  So run both and keep the
            # better one -- this can never be worse than the notebook.
            s_on_bound = (abs(s_fit - s_lo) < 1e-6 or abs(s_fit - s_hi) < 1e-6)
            s_rescued = False
            s_flat = False
            s_unidentified = False
            s_span = float("nan")
            s_obj_lbfgs = float("nan")
            s_obj_grid = float("nan")
            if cfg.s0 is None and cfg.s_estimator != "lbfgs":
                g_lo = max(cfg.s_profile_lo, s_lo)
                g_hi = min(cfg.s_profile_hi, s_hi)
                spg = profile_s(
                    rho_r, u_r, centers_ref, P_ref,
                    s_grid=np.linspace(g_lo, g_hi, cfg.s_guard_n),
                    sigma_x=cfg.sigma_x, r_penalty=cfg.r_penalty,
                    w_asym=cfg.w_asym)
                sg, og = spg["s_grid"], spg["obj"]
                s_span = float(np.max(og) - np.min(og))
                s_flat = bool(s_span < cfg.s_identifiable_span
                              * max(float(np.min(og)), 1e-12))
                j = int(np.argmin(og))

                # Does the objective have an INTERIOR minimum on the physical
                # branch?  If it slides to an edge instead, s is not determined
                # by these data, and "rescuing" it to the edge would be worse
                # than the runaway it replaces -- it would look converged.
                # Say so and fall back to a fixed value.
                s_unidentified = bool(j == 0 or j == sg.size - 1 or s_flat)

                if s_unidentified:
                    fallback = (float(cfg.s0) if cfg.s0 is not None
                                else float(cfg.s_fallback))
                    print(f"[s-guard] NOT IDENTIFIABLE at L={cfg.L}, "
                          f"eps_d={eps_sp:.4f}: the fit objective has no "
                          f"interior minimum on the physical branch "
                          f"[{g_lo:+.4f}, {g_hi:+.4f}] "
                          f"(min at the {'lower' if j == 0 else 'upper'} edge, "
                          f"span {s_span:.4g}).  Falling back to "
                          f"s = {fallback:+.5f}.  Pass --s0 with the logged "
                          f"trace value to make this explicit.", flush=True)
                    s_fit = fallback
                    s_rescued = True
                else:
                    s_grid_min = float(sg[j])
                    cq = np.polyfit(sg[j - 1:j + 2], og[j - 1:j + 2], 2)
                    if cq[0] > 0:
                        cand = -0.5 * cq[1] / cq[0]
                        if sg[0] <= cand <= sg[-1]:
                            s_grid_min = float(cand)
                    pair = profile_s(rho_r, u_r, centers_ref, P_ref,
                                     s_grid=np.array([s_fit, s_grid_min]),
                                     sigma_x=cfg.sigma_x,
                                     r_penalty=cfg.r_penalty,
                                     w_asym=cfg.w_asym)
                    s_obj_lbfgs = float(pair["obj"][0])
                    s_obj_grid = float(pair["obj"][1])
                    if (cfg.s_estimator == "grid"
                            or s_obj_grid < s_obj_lbfgs):
                        if verbose:
                            print(f"[s-guard] L-BFGS-B s={s_fit:+.5f} "
                                  f"(obj {s_obj_lbfgs:.5g})"
                                  f"{'  ON BOUND' if s_on_bound else ''}"
                                  f"  ->  grid s={s_grid_min:+.5f} "
                                  f"(obj {s_obj_grid:.5g})", flush=True)
                        s_rescued = bool(abs(s_grid_min - s_fit) > 1e-4)
                        s_fit = s_grid_min

            s_use = s_fit if cfg.s0 is None else float(cfg.s0)
            s_ref = s_use

            Mprime = rho_r - s_use * u_r
            Mc = float(Mprime.mean())
            lambdap = 1.0 - s_use * r_fit

            # --- 5. reweight (eps_nd, mu) from eps_sp_prev to eps_sp -----
            theta_ref = (eps_ns, eps_sp_prev, mu_star, lambdap, Mc, s_use)
            d_eps_d = float(eps_sp) - float(eps_sp_prev)
            relocating = abs(d_eps_d) < 1e-12
            curvature = float("nan")

            if relocating:
                # Zero displacement: L-BFGS-B cannot move here (the objective
                # is piecewise constant and it starts at the minimum of its own
                # starting bin), so go straight to the scan.  The window is the
                # finite-size rounding width, not the eps_d step.
                half = cfg.relocate_halfwidth
                if cfg.relocate_scale_with_L:
                    half *= float(cfg.L_ref) / float(cfg.L)
                half_mu = cfg.relocate_mu_halfwidth
                sc = scan_eps_mu_fixed_epsA_fixed_s(
                    theta_ref, eps_sp, rho_r, u_r, C_r, Ca_r, N_r,
                    edges_ref, P_ref,
                    eps_halfwidth=half, mu_halfwidth=half_mu,
                    n_eps=cfg.relocate_n_eps, n_mu=cfg.relocate_n_mu,
                    ess_floor=cfg.relocate_ess_floor,
                    mu_mode=cfg.scan_mu_mode,
                    dilute_window=cfg.dilute_window,
                    dense_window=cfg.dense_window,
                    verbose=verbose)
                eps_ns_new, mu_new, js = sc["eps_nd"], sc["mu"], sc["js"]
                curvature = float(sc["curvature"])
                stalled = False
                rescued = False
                at_bound = bool(sc["at_edge"])
                # A scan always "succeeds"; what says whether it found a real
                # minimum is the curvature (nan == no interior parabola) and
                # at_bound.
                opt_success = bool(np.isfinite(curvature) and not at_bound)
                if verbose:
                    print(f"[relocate] window +-{half:.4f} in eps_nd, "
                          f"+-{half_mu:.4f} in mu;  moved "
                          f"{eps_ns_new - eps_ns:+.6f}", flush=True)

                if cfg.store_diagnostics:
                    sp = profile_s(
                        rho_r, u_r, centers_ref, P_ref,
                        s_grid=np.linspace(cfg.s_profile_lo, cfg.s_profile_hi,
                                           cfg.s_profile_n),
                        sigma_x=cfg.sigma_x, r_penalty=cfg.r_penalty,
                        w_asym=cfg.w_asym)
                    j_fit = int(np.argmin(np.abs(sp["s_grid"] - s_use)))
                    j_min = int(np.argmin(sp["obj"]))
                    diag_arrays.update({
                        "scan_eps": sc["eps_grid"], "scan_js": sc["prof"],
                        "scan_mu": sc["mu_at"], "scan_ess": sc["ess"],
                        "scan_halfwidth": np.array([half]),
                        "scan_admissible": sc["admissible"],
                        "scan_frac_admissible":
                            np.array([sc["frac_admissible"]]),
                        "scan_eps_anchor": np.array([eps_ns]),
                        "s_grid": sp["s_grid"], "s_obj": sp["obj"],
                        "s_match": sp["match"], "s_asym": sp["asym"],
                        "s_fitted": np.array([s_use]),
                        "s_argmin": np.array([sp["s_grid"][j_min]]),
                        "P_at_s_fitted": sp["P"][j_fit],
                        "P_at_s_argmin": sp["P"][j_min],
                        "P_at_s_zero": sp["P"][
                            int(np.argmin(np.abs(sp["s_grid"])))],
                        "reloc_rho": np.asarray(rho_r, np.float32),
                        "reloc_u": np.asarray(u_r, np.float32),
                        # Everything needed to rebuild, exactly, the histogram
                        # the JS objective compares against P*(x): the counts
                        # that carry the reweighting, and both theta vectors.
                        "reloc_C_ns": np.asarray(C_r, np.float32),
                        "reloc_C_sp": np.asarray(Ca_r, np.float32),
                        "reloc_N_mu": np.asarray(N_r, np.float32),
                        "theta_ref": np.asarray(theta_ref, float),
                        "theta_star": np.asarray(
                            [eps_ns_new, eps_sp, mu_new, 1.0, Mc, s_use],
                            float),
                    })
                    if verbose:
                        print(f"[s-profile] fitted s={s_use:+.5f} "
                              f"(obj {sp['obj'][j_fit]:.5g})   "
                              f"grid argmin s={sp['s_grid'][j_min]:+.5f} "
                              f"(obj {sp['obj'][j_min]:.5g})", flush=True)
            else:
                half = cfg.opt_halfwidth_per_step * abs(cfg.eps_sp_step)
                half_mu = half
                res = optimize_eps_mu_Mc_fixed_epsA_fixed_s(
                    theta_ref, eps_sp, rho_r, u_r, C_r, Ca_r, N_r,
                    edges_ref, P_ref, L_fixed=None,
                    eps_halfwidth=half, mu_halfwidth=half_mu)
                eps_ns_new, _, mu_new, _, _, _ = res.theta_star
                js = float(res.fun)
                opt_success = bool(res.success)

                stalled = bool(abs(float(eps_ns_new) - eps_ns) < cfg.stall_tol)
                at_bound = bool(
                    abs(abs(float(eps_ns_new) - eps_ns) - half) < 1e-9)
                rescued = False

                if stalled and cfg.scan_fallback:
                    sc = scan_eps_mu_fixed_epsA_fixed_s(
                        theta_ref, eps_sp, rho_r, u_r, C_r, Ca_r, N_r,
                        edges_ref, P_ref, eps_halfwidth=half,
                        mu_halfwidth=half_mu, verbose=verbose)
                    if sc["js"] <= js:
                        eps_ns_new, mu_new, js = (sc["eps_nd"], sc["mu"],
                                                  sc["js"])
                        curvature = float(sc["curvature"])
                        rescued = True

            d_eps = float(eps_ns_new) - eps_ns
            eps_clamped = bool(abs(d_eps) > cfg.max_abs_eps_step)
            if eps_clamped:
                # This must be flagged, not just warned about: a clamped step
                # reports eps_nd = anchor +- max_abs_eps_step EXACTLY, which
                # looks like a located value and is not one.
                print(f"[warn] |d eps_nd| = {abs(d_eps):.4f} exceeds "
                      f"max_abs_eps_step={cfg.max_abs_eps_step}; CLAMPING -- "
                      f"the reported eps_nd is the clamp, not a minimum",
                      flush=True)
                eps_ns_new = eps_ns + math.copysign(cfg.max_abs_eps_step, d_eps)

            eps_ns = float(eps_ns_new)
            mu = float(mu_new)

            rec = dict(
                index=i,
                mode=("relocate" if relocating else "continuation"),
                d_eps_d=float(d_eps_d),
                curvature=float(curvature),
                eps_d=float(eps_sp),
                eps_d_prev=float(eps_sp_prev),
                eps_nd=float(eps_ns),
                mu=float(mu),
                mu_star_ref=float(mu_star),
                s=float(s_use),
                s_fit=float(s_fit),
                s_on_bound=bool(s_on_bound),
                s_rescued=bool(s_rescued),
                s_obj_lbfgs=float(s_obj_lbfgs),
                s_obj_grid=float(s_obj_grid),
                eps_clamped=bool(eps_clamped),
                s_flat=bool(s_flat),
                s_unidentified=bool(s_unidentified),
                s_span=float(s_span),
                s_lo=float(s_lo),
                s_hi=float(s_hi),
                s_singularity=float(s_sing),
                s_sigma_min_ratio=float(s_sigmin),
                s_fixed=bool(cfg.s0 is not None),
                r=float(r_fit),
                lam=float(lambdap),
                Mc=float(Mc),
                js=float(js),
                ess_mu=float(ess_mu),
                ess_frac=float(ess_mu / max(len(rho), 1)),
                mu_equal_area=float(guard["mu"]),
                mu_scout_ok=bool(guard["success"]),
                n_scout_sims=int(guard.get("n_sim", 0)),
                mean_rho=float(np.mean(rho)),
                min_crossings=int(diag["min_crossings"]),
                total_crossings=int(diag["total_crossings"]),
                mean_accept=float(diag["mean_accept"]),
                rho_spread=float(diag["rho_spread"]),
                opt_success=bool(opt_success),
                stalled=stalled,
                at_bound=at_bound,
                rescued_by_scan=rescued,
                fit_success=bool(fit["success"]),
                match_L2=float(fit["match_L2"]),
                asym_L2=float(fit["asym_L2"]),
                steps_per_replica=int(P_prod["steps"]),
                wall_seconds=float(time.perf_counter() - t_step),
            )
            points.append(rec)
            if cfg.archive_raw:
                last_raw = diag.get("raw", {})

            if verbose:
                flags = []
                if stalled:
                    flags.append("STALLED" + ("->rescued" if rescued else ""))
                if at_bound:
                    flags.append("AT-BOUND")
                if rec["min_crossings"] < cfg.min_crossings_warn:
                    flags.append("NO-TUNNELLING")
                if rec["ess_frac"] < 0.10:
                    flags.append("LOW-ESS")
                if relocating:
                    flags.append("RELOCATE")
                if s_rescued:
                    flags.append("S-RESCUED" + ("(bound)" if s_on_bound
                                                else ""))
                if s_unidentified:
                    flags.append("S-NOT-IDENTIFIABLE")
                if eps_clamped:
                    flags.append("EPS-CLAMPED")
                tag = ("  [" + " ".join(flags) + "]") if flags else ""
                print(f"[step {i + 1}/{grid.size}] eps_d={eps_sp:.4f}  "
                      f"eps_nd={eps_ns:.6f}  mu={mu:.6f}  s={s_use:.4f}  "
                      f"JS={js:.5f}  ESS/n={rec['ess_frac']:.2f}  "
                      f"cross(min)={rec['min_crossings']}  "
                      f"<rho>={rec['mean_rho']:.3f}  "
                      f"{rec['wall_seconds']:.0f}s{tag}", flush=True)

            eps_sp_prev = eps_sp

            if cfg.checkpoint:
                tmp = cfg.checkpoint + ".tmp"
                with open(tmp, "w") as fh:
                    json.dump(dict(points=points, eps_ns=eps_ns, mu=mu,
                                   eps_sp_prev=eps_sp_prev, s_ref=s_ref,
                                   next_index=i + 1, L=cfg.L,
                                   system=cfg.system, seed=cfg.seed,
                                   code_version=MC_LINE_VERSION,
                                   fingerprint=_ckpt_fingerprint(cfg)), fh)
                os.replace(tmp, cfg.checkpoint)
    finally:
        pool.close()
        pool.join()

    return dict(
        system=cfg.system, L=cfg.L, seed=cfg.seed,
        eps_sp_start=cfg.eps_sp_start, eps_sp_end=cfg.eps_sp_end,
        eps_sp_step=cfg.eps_sp_step,
        eps_nd_anchor=(cfg.eps_ns0 if cfg.eps_ns0 is not None else eps_ns0),
        mu_anchor=(cfg.mu0 if cfg.mu0 is not None else mu0),
        points=points,
        complete=bool(len(points) >= grid.size),
        steps_per_replica=steps_prod,
        sweeps_per_replica=steps_prod / float(cfg.L ** 2),
        n_replicas=cfg.n_replicas,
        centers_ref=centers_ref, edges_ref=edges_ref, P_ref=P_ref,
        raw=last_raw,
        diag_arrays=diag_arrays,
    )
